define(
//begin v1.x content
{
	"BRE_displayName": "Κρουζιέρο Βραζιλίας (1990–1993)",
	"DEM_displayName": "Μάρκο Γερμανίας",
	"CUP_displayName": "Πέσο Κούβας",
	"PYG_displayName": "Γκουαρανί Παραγουάης",
	"MDL_displayName": "Λέου Μολδαβίας",
	"DOP_displayName": "Πέσο Δομινικανής Δημοκρατίας",
	"NGN_displayName": "Νάιρα Νιγηρίας",
	"KZT_displayName": "Τένγκε Καζακστάν",
	"LTT_displayName": "Ταλόνας Λιθουανίας",
	"LAK_displayName": "Κιπ Λάος",
	"LKR_displayName": "Ρουπία Σρι Λάνκα",
	"XEU_displayName": "Ευρωπαϊκή Συναλλαγματική Μονάδα",
	"XOF_symbol": "CFA",
	"USS_displayName": "Δολάριο ΗΠΑ (ίδια ημέρα)",
	"MNT_displayName": "Τουγκρίκ Μογγολίας",
	"RHD_displayName": "Δολάριο Ροδεσίας",
	"MOP_displayName": "Πατάκα Μακάο",
	"TJR_displayName": "Ρούβλι Τατζικιστάν",
	"LUC_displayName": "Μετατρέψιμο Φράγκο Λουξεμβούργου",
	"LUL_displayName": "Οικονομικό Φράγκο Λουξεμβούργου",
	"AON_displayName": "Νέα Κουάνζα Ανγκόλας (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "Φράγκο Βελγίου",
	"GHS_displayName": "Σέντι Γκάνας",
	"IEP_displayName": "Λίρα Ιρλανδίας",
	"SBD_displayName": "Δολάριο Νήσων Σολομώντος",
	"GRD_displayName": "Δραχμή Ελλάδας",
	"NIC_displayName": "Κόρδοβα Νικαράγουας",
	"AZM_displayName": "Μανάτ Αζερμπαϊτζάν (1993–2006)",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "Λίρα Μάλτας",
	"LVR_displayName": "Ρούβλι Λετονίας",
	"GNF_displayName": "Φράγκο Γουινέας",
	"GIP_displayName": "Λίρα Γιβραλτάρ",
	"SRG_displayName": "Γκίλντα Σουρινάμ",
	"BAD_displayName": "Δηνάριο Βοσνίας-Ερζεγοβίνης",
	"FJD_displayName": "Δολάριο Φίτζι",
	"BAM_displayName": "Μετατρέψιμο Μάρκο Βοσνίας-Ερζεγοβίνης",
	"XBB_displayName": "Ευρωπαϊκή Νομισματική Μονάδα",
	"CDF_displayName": "Φράγκο Κονγκό",
	"HRD_displayName": "Δηνάριο Κροατίας",
	"BZD_displayName": "Δολάριο Μπελίζ",
	"MLF_displayName": "Φράγκο Μαλί",
	"EGP_displayName": "Λίρα Αιγύπτου",
	"MVR_displayName": "Ρουφίγια Μαλδίβων",
	"TRY_displayName": "Τουρκική Λίρα",
	"ILR_displayName": "παλιό σεκέλ Ισραήλ",
	"SDP_displayName": "Παλαιά Λίρα Σουδάν",
	"NPR_displayName": "Ρουπία Νεπάλ",
	"PHP_displayName": "Πέσο Φιλιππίνων",
	"WST_displayName": "Τάλα Σαμόα",
	"TRL_displayName": "Παλιά Λίρα Τουρκίας",
	"JPY_displayName": "Γιεν Ιαπωνίας",
	"TMM_displayName": "Μανάτ Τουρκμενιστάν",
	"BGN_displayName": "Λεβ Βουλγαρίας",
	"KYD_displayName": "Δολάριο Νήσων Κάιμαν",
	"VUV_displayName": "Βατού Βανουάτου",
	"IRR_displayName": "Ριάλ Ιράν",
	"DJF_displayName": "Φράγκο Τζιμπουτί",
	"XDR_displayName": "Ειδικά Δικαιώματα Ανάληψης",
	"ECS_displayName": "Σούκρε Εκουαδόρ",
	"HKD_symbol": "HK$",
	"NLG_displayName": "Γκίλντα Ολλανδίας",
	"ISJ_displayName": "Παλιά κορόνα Ισλανδίας",
	"MWK_displayName": "Κουάτσα Μαλάουι",
	"HTG_displayName": "Γκουρντ Αϊτής",
	"PES_displayName": "Σολ Περού",
	"LYD_displayName": "Δηνάριο Λιβύης",
	"BRR_displayName": "Κρουζιέρο Βραζιλίας",
	"XXX_displayName": "Άγνωστο νόμισμα",
	"IDR_displayName": "Ρουπία Ινδονησίας",
	"USD_displayName": "Δολάριο ΗΠΑ",
	"KGS_displayName": "Σομ Κιργιζίας",
	"BRN_displayName": "Νέο Κρουζάντο Βραζιλίας",
	"CHF_displayName": "Φράγκο Ελβετίας",
	"ISK_displayName": "Κορόνα Ισλανδίας",
	"LUF_displayName": "Φράγκο Λουξεμβούργου",
	"GRD_pattern": "#,##0.00 ¤",
	"MXN_symbol": "MX$",
	"SVC_displayName": "Κολόν Ελ Σαλβαδόρ",
	"ZMK_displayName": "Κουάνζα Ζαΐρ (1968–2012)",
	"TOP_displayName": "Παάγκα νήσων Τόγκα",
	"ITL_displayName": "Λιρέτα Ιταλίας",
	"USN_displayName": "Δολάριο ΗΠΑ (επόμενη ημέρα)",
	"VND_symbol": "₫",
	"KWD_displayName": "Δηνάριο Κουβέιτ",
	"NIO_displayName": "Χρυσή Κόρδοβα Νικαράγουας",
	"KMF_displayName": "Φράγκο Κομορών",
	"MYR_displayName": "Ρινγκίτ Μαλαισίας",
	"XFU_displayName": "UIC-Φράγκο Γαλλίας",
	"GMD_displayName": "Νταλάσι Γκάμπιας",
	"LVL_displayName": "Λατς Λετονίας",
	"AUD_displayName": "Δολάριο Αυστραλίας",
	"XPF_displayName": "Φράγκο CFP",
	"LBP_displayName": "Λίρα Λιβάνου",
	"BYB_displayName": "Νέο Ρούβλι Λευκορωσίας (1994–1999)",
	"MKD_displayName": "Δηνάριο Π.Γ.Δ.Μ.",
	"GWP_displayName": "Πέσο Γουινέας-Μπισάου",
	"CNY_displayName": "Γουάν Κίνας",
	"MAF_displayName": "Φράγκο Μαρόκου",
	"JOD_displayName": "Δηνάριο Ιορδανίας",
	"OMR_displayName": "Ριάλ Ομάν",
	"BOV_displayName": "Μβδολ Βολιβίας",
	"AUD_symbol": "A$",
	"NOK_displayName": "Κορόνα Νορβηγίας",
	"SCR_displayName": "Ρουπία Σεϋχελλών",
	"XBA_displayName": "Ευρωπαϊκή Σύνθετη Μονάδα",
	"CSK_displayName": "Σκληρή Κορόνα Τσεχοσλοβακίας",
	"PLZ_displayName": "Ζλότυ Πολωνίας (1950–1995)",
	"UAK_displayName": "Καρμποβανέτς Ουκρανίας",
	"MGF_displayName": "Φράγκο Μαδαγασκάρης",
	"GNS_displayName": "Συλί Γουινέας",
	"YUN_displayName": "Μετατρέψιμο Δηνάριο Γιουγκοσλαβίας",
	"GYD_displayName": "Δολάριο Γουιάνας",
	"QAR_displayName": "Ριάλ Κατάρ",
	"ALL_displayName": "Λεκ Αλβανίας",
	"BBD_displayName": "Δολάριο Μπαρμπάντος",
	"SSP_displayName": "Λίρα Νότιου Σουδάν",
	"GRD_decimal": ",",
	"RON_displayName": "Λέου Ρουμανίας",
	"XCD_symbol": "EC$",
	"AMD_displayName": "Ντραμ Αρμενίας",
	"CYP_displayName": "Λίρα Κύπρου",
	"GBP_symbol": "£",
	"SEK_displayName": "Κορόνα Σουηδίας",
	"MMK_displayName": "Κυάτ Μιανμάρ",
	"ZAR_displayName": "Ραντ Νότιας Αφρικής",
	"AWG_displayName": "Φλορίνι Αρούμπα",
	"STD_displayName": "Ντόμπρα Σάο Τομέ και Πρίνσιπε",
	"CAD_displayName": "Δολάριο Καναδά",
	"ADP_displayName": "Πεσέτα Ανδόρας",
	"MRO_displayName": "Ουγκίγια Μαυριτανίας",
	"ESB_displayName": "πεσέτα Ισπανίας (μετατρέψιμος λογαριασμός)",
	"LSL_displayName": "Λότι Λεσότο",
	"TND_displayName": "Δηνάριο Τυνησίας",
	"USD_symbol": "$",
	"BRC_displayName": "Κρουζάντο Βραζιλίας",
	"BMD_displayName": "Δολάριο Βερμούδων",
	"BRL_displayName": "Ρεάλ Βραζιλίας",
	"JMD_displayName": "Δολάριο Τζαμάικας",
	"SOS_displayName": "Σελίνι Σομαλίας",
	"SAR_displayName": "Ριάλ Σαουδικής Αραβίας",
	"PEI_displayName": "Ίντι Περού",
	"ESP_displayName": "Πεσέτα Ισπανίας",
	"HKD_displayName": "Δολάριο Χονγκ Κονγκ",
	"BWP_displayName": "Πούλα Μποτσουάνας",
	"TTD_displayName": "Δολάριο Τρινιντάντ και Τομπάγκο",
	"BSD_displayName": "Δολάριο Μπαχάμες",
	"BIF_displayName": "Φράγκο Μπουρούντι",
	"FRF_displayName": "Φράγκο Γαλλίας",
	"DKK_displayName": "Κορόνα Δανίας",
	"AED_displayName": "Ντιράμ Ηνωμένων Αραβικών Εμιράτων",
	"AOK_displayName": "Κουάνζα Ανγκόλας (1977–1990)",
	"ATS_displayName": "Σελίνι Αυστρίας",
	"PEN_displayName": "Νέο Σολ Περού",
	"CRC_displayName": "Κολόν Κόστα Ρίκα",
	"PAB_displayName": "Μπαλμπόα Παναμά",
	"CHE_displayName": "Ευρώ WIR",
	"GQE_displayName": "Εκγουέλε Ισημερινής Γουινέας",
	"DZD_displayName": "Δηνάριο Αλγερίας",
	"EEK_displayName": "Κορόνα Εσθονίας",
	"GRD_symbol": "Δρχ",
	"YDD_displayName": "Δηνάριο Υεμένης",
	"GHC_displayName": "Σέντι Γκάνας (1979–2007)",
	"MXP_displayName": "Ασημένιο Πέσο Μεξικού (1861–1992)",
	"AFN_displayName": "Αφγάνι Αφγανιστάν",
	"XFO_displayName": "Χρυσό Φράγκο Γαλλίας",
	"GWE_displayName": "Γκινέα Εσκούδο Πορτογαλίας",
	"BOB_displayName": "Μπολιβιάνο Βολιβίας",
	"CAD_symbol": "CA$",
	"VND_displayName": "Ντονγκ Βιετνάμ",
	"AFA_displayName": "Αφγανί Αφγανιστάν (1927–2002)",
	"ZWD_displayName": "Δολάριο Ζιμπάμπουε",
	"JPY_symbol": "JP¥",
	"SRD_displayName": "Δολάριο Σουρινάμ",
	"ZRN_displayName": "Νέο Ζαΐρ Ζαΐρ",
	"KRW_symbol": "₩",
	"BOP_displayName": "Πέσο Βολιβίας",
	"XBD_displayName": "Ευρωπαϊκή μονάδα λογαριασμού (XBD)",
	"TZS_displayName": "Σελίνι Τανζανίας",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "Λέι Ρουμανίας",
	"LRD_displayName": "Δολάριο Λιβερίας",
	"KRW_displayName": "Γουόν Νότιας Κορέας",
	"SHP_displayName": "Λίρα Αγίας Ελένης",
	"MZE_displayName": "Εσκούδο Μοζαμβίκης",
	"MZN_displayName": "Μετικάλ Μοζαμβίκης",
	"SDD_displayName": "Δηνάριο Σουδάν",
	"HRK_displayName": "Κούνα Κροατίας",
	"FKP_displayName": "Λίρα Νησιών Φώκλαντ",
	"COP_displayName": "Πέσο Κολομβίας",
	"YUD_displayName": "Μεταλλικό Δηνάριο Γιουγκοσλαβίας",
	"YUM_displayName": "Νέο Δηνάριο Γιουγκοσλαβίας",
	"THB_displayName": "Μπατ Ταϊλάνδης",
	"UZS_displayName": "Σομ Ουζμπεκιστάν",
	"MGA_displayName": "Αριάρι Μαδαγασκάρης",
	"TWD_displayName": "Νέο δολάριο Ταϊβάν",
	"UGS_displayName": "Σελίνι Ουγκάντας (1966–1987)",
	"ZAL_displayName": "Ραντ Νότιας Αφρικής (οικονομικό)",
	"GEL_displayName": "Λάρι Γεωργίας",
	"ILP_displayName": "Λίρα Ισραήλ",
	"DDM_displayName": "Οστμάρκ Ανατολικής Γερμανίας",
	"KES_displayName": "Σελίνι Κένυας",
	"CUC_displayName": "Μετατρέψιμο πέσο Κούβας",
	"CZK_displayName": "Κορόνα Τσεχίας",
	"UGX_displayName": "Σελίνι Ουγκάντας",
	"ILS_symbol": "₪",
	"TMT_displayName": "Μάνατ Τουρκμενιστάν",
	"THB_symbol": "฿",
	"BGL_displayName": "Μεταλλικό Λεβ Βουλγαρίας",
	"ARP_displayName": "Πέσο Αργεντινής (1983–1985)",
	"RUR_displayName": "Ρούβλι Ρωσίας (1991–1998)",
	"ERN_displayName": "Νάκφα Ερυθραίας",
	"ESA_displayName": "πεσέτα Ισπανίας (λογαριασμός Α)",
	"CLF_displayName": "Ουνιδάδες ντε φομέντο Χιλής",
	"BRB_displayName": "Νέο Κρουζιέρο Βραζιλίας (1967–1986)",
	"BHD_displayName": "Δηνάριο Μπαχρέιν",
	"SYP_displayName": "Λίρα Συρίας",
	"SZL_displayName": "Λιλανγκένι Σουαζιλάνδης",
	"INR_displayName": "Ρουπία Ινδίας",
	"PTE_displayName": "Εσκούδο Πορτογαλίας",
	"KPW_displayName": "Γουόν Βόρειας Κορέας",
	"XOF_displayName": "Φράγκο CFA Δυτικής Αφρικής",
	"MXN_displayName": "Πέσο Μεξικού",
	"RWF_displayName": "Φράγκο Ρουάντας",
	"ETB_displayName": "Μπιρ Αιθιοπίας",
	"LTL_displayName": "Λίτα Λιθουανίας",
	"BND_displayName": "Δολάριο Μπρουνέι",
	"SUR_displayName": "Σοβιετικό Ρούβλι",
	"SKK_displayName": "Κορόνα Σλοβενίας",
	"AOA_displayName": "Κουάνζα Ανγκόλας",
	"CVE_displayName": "Εσκούδο Πράσινου Ακρωτηρίου",
	"BRL_symbol": "R$",
	"CLP_displayName": "Πέσο Χιλής",
	"HUF_displayName": "Φιορίνι Ουγγαρίας",
	"GRD_group": ".",
	"TJS_displayName": "Σομόνι Τατζικιστάν",
	"GBP_displayName": "Λίρα Στερλίνα Βρετανίας",
	"TPE_displayName": "Εσκούδο Τιμόρ",
	"BDT_displayName": "Τάκα Μπαγκλαντές",
	"SGD_displayName": "Δολάριο Σιγκαπούρης",
	"SLL_displayName": "Λεόνε Σιέρα Λεόνε",
	"XAF_displayName": "Φράγκο CFA Κεντρικής Αφρικής",
	"MTL_displayName": "Λιρέτα Μάλτας",
	"KHR_displayName": "Ρίελ Καμπότζης",
	"ZRZ_displayName": "Ζαΐρ Ζαΐρ",
	"RSD_displayName": "Δηνάριο Σερβίας",
	"BEC_displayName": "Φράγκο Βελγίου (μετατρέψιμο)",
	"BEL_displayName": "Φράγκο Βελγίου (οικονομικό)",
	"AZN_displayName": "Μανάτ Αζερμπαϊτζάν",
	"FIM_displayName": "Μάρκο Φινλανδίας",
	"ZWL_displayName": "Δολάριο Ζιμπάμπουε (2009)",
	"PKR_displayName": "Ρουπία Πακιστάν",
	"UYP_displayName": "Πέσο Ουρουγουάης (1975–1993)",
	"ZMW_displayName": "Κουάτσα Ζάμπιας",
	"CHW_displayName": "Φράγκο WIR",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "Ζλότι Πολωνίας",
	"UAH_displayName": "Γρίβνα Ουκρανίας",
	"BTN_displayName": "Νγκούλτρουμ Μπουτάν",
	"YER_displayName": "Ριάλ Υεμένης",
	"UYU_displayName": "Πέσο Ουρουγουάης",
	"CSD_displayName": "Παλαιό Δηνάριο Σερβίας",
	"VEF_displayName": "Μπολιβάρ Βενεζουέλας",
	"PGK_displayName": "Κίνα Παπούα Νέα Γουινέα",
	"XBC_displayName": "Ευρωπαϊκή μονάδα λογαριασμού (XBC)",
	"EUR_displayName": "Ευρώ",
	"MUR_displayName": "Ρουπία Μαυρικίου",
	"MAD_displayName": "Ντιράμ Μαρόκου",
	"SDG_displayName": "Λίρα Σουδάν",
	"BYR_displayName": "Ρούβλι Λευκορωσίας",
	"VEB_displayName": "Μπολιβάρ Βενεζουέλας (1871–2008)",
	"IQD_displayName": "Δηνάριο Ιράκ",
	"MZM_displayName": "Παλαιό Μετικάλ Μοζαμβίκης",
	"NZD_symbol": "NZ$",
	"SIT_displayName": "Τόλαρ Σλοβενίας",
	"XCD_displayName": "Δολάριο Ανατολικής Καραϊβικής",
	"RUB_displayName": "Ρούβλι Ρωσίας",
	"BUK_displayName": "Κιατ Βιρμανίας",
	"ILS_displayName": "Νέο Σέκελ Ισραήλ",
	"INR_symbol": "₹",
	"NAD_displayName": "Δολάριο Ναμίμπια",
	"HNL_displayName": "Λεμπίρα Ονδούρας",
	"GTQ_displayName": "Κουετσάλ Γουατεμάλας",
	"GEK_displayName": "Κούπον Λάρι Γεωργίας",
	"EUR_symbol": "€",
	"NZD_displayName": "Δολάριο Νέας Ζηλανδίας",
	"ARA_displayName": "Ωστράλ Αργετινής",
	"ARS_displayName": "Πέσο Αργεντινής",
	"ANG_displayName": "Γκίλντα Ολλανδικών Αντιλλών"
}
//end v1.x content
);