define(
//begin v1.x content
{
	"BRE_displayName": "Brazil cruzeiro (1990–1993)",
	"DEM_displayName": "Német márka",
	"CUP_displayName": "kubai peso",
	"HUF_symbol": "Ft",
	"PYG_displayName": "paraguayi guarani",
	"MDL_displayName": "moldován lei",
	"DOP_displayName": "dominikai peso",
	"NGN_displayName": "nigériai naira",
	"KZT_displayName": "kazahsztáni tenge",
	"MXV_displayName": "Mexikói Unidad de Inversion (UDI)",
	"LTT_displayName": "Litvániai talonas",
	"LAK_displayName": "laoszi kip",
	"LKR_displayName": "Srí Lanka-i rúpia",
	"AOR_displayName": "Angolai kwanza reajustado (1995–1999)",
	"XEU_displayName": "európai pénznemegység",
	"XOF_symbol": "CFA",
	"USS_displayName": "USA dollár (aznapi)",
	"MNT_displayName": "mongóliai tugrik",
	"RHD_displayName": "rhodéziai dollár",
	"MOP_displayName": "makaói pataca",
	"TJR_displayName": "Tádzsikisztáni rubel",
	"LUC_displayName": "luxemburgi konvertibilis frank",
	"LUL_displayName": "luxemburgi pénzügyi frank",
	"AON_displayName": "Angolai új kwanza (1990–2000)",
	"TWD_symbol": "TWD",
	"BEF_displayName": "Belga frank",
	"GHS_displayName": "ghánai cedi",
	"IEP_displayName": "Ír font",
	"SBD_displayName": "salamon-szigeteki dollár",
	"GRD_displayName": "Görög drachma",
	"NIC_displayName": "Nikaraguai cordoba",
	"AZM_displayName": "azerbajdzsáni manat (1993–2006)",
	"CNY_symbol": "CNY",
	"MTP_displayName": "Máltai font",
	"LVR_displayName": "Lett rubel",
	"GNF_displayName": "guineai frank",
	"GIP_displayName": "gibraltári font",
	"SRG_displayName": "Suriname-i gulden",
	"BAD_displayName": "Bosznia-hercegovinai dínár (1992–1994)",
	"FJD_displayName": "fidzsi dollár",
	"BAM_displayName": "bosznia-hercegovinai konvertibilis márka",
	"XBB_displayName": "Európai monetáris egység",
	"CDF_displayName": "kongói frank",
	"HRD_displayName": "Horvát dínár",
	"BZD_displayName": "belize-i dollár",
	"MLF_displayName": "Mali frank",
	"EGP_displayName": "egyiptomi font",
	"MVR_displayName": "maldív-szigeteki rufiyaa",
	"TRY_displayName": "török líra",
	"SDP_displayName": "Szudáni font (1957–1998)",
	"XRE_displayName": "RINET tőke",
	"NPR_displayName": "nepáli rúpia",
	"PHP_displayName": "fülöp-szigeteki peso",
	"WST_displayName": "nyugat-szamoai tala",
	"TRL_displayName": "török líra (1922–2005)",
	"JPY_displayName": "japán jen",
	"TMM_displayName": "türkmenisztáni manat (1993–2009)",
	"BGN_displayName": "bolgár új leva",
	"KYD_displayName": "kajmán-szigeteki dollár",
	"VUV_displayName": "vanuatui vatu",
	"IRR_displayName": "iráni rial",
	"DJF_displayName": "dzsibuti frank",
	"XDR_displayName": "Special Drawing Rights",
	"ECS_displayName": "Ecuadori sucre",
	"HKD_symbol": "HKD",
	"NLG_displayName": "Holland forint",
	"MWK_displayName": "malawi kwacha",
	"HTG_displayName": "haiti gourde",
	"PES_displayName": "Perui sol",
	"LYD_displayName": "líbiai dínár",
	"BRR_displayName": "Brazil cruzeiro (1993–1994)",
	"XXX_displayName": "ismeretlen pénznem",
	"IDR_displayName": "indonéz rúpia",
	"USD_displayName": "USA-dollár",
	"KGS_displayName": "kirgizisztáni szom",
	"BRN_displayName": "Brazil cruzado novo (1989–1990)",
	"CHF_displayName": "svájci frank",
	"ISK_displayName": "izlandi korona",
	"LUF_displayName": "Luxemburgi frank",
	"MXN_symbol": "MXN",
	"SVC_displayName": "Salvadori colón",
	"ZMK_displayName": "Zambiai kwacha (1968–2012)",
	"ZWR_displayName": "Zimbabwei dollár (2008)",
	"TOP_displayName": "tongai paanga",
	"ITL_displayName": "Olasz líra",
	"USN_displayName": "USA dollár (következő napi)",
	"VND_symbol": "VND",
	"KWD_displayName": "kuvaiti dínár",
	"NIO_displayName": "nicaraguai córdoba",
	"KMF_displayName": "comorei frank",
	"UYI_displayName": "Uruguayi peso en unidades indexadas",
	"MYR_displayName": "malajziai ringgit",
	"XFU_displayName": "Francia UIC-frank",
	"GMD_displayName": "gambiai dalasi",
	"LVL_displayName": "lett lats",
	"AUD_displayName": "ausztrál dollár",
	"XPF_displayName": "csendes-óceáni valutaközösségi frank",
	"LBP_displayName": "libanoni font",
	"BYB_displayName": "Fehérorosz új rubel (1994–1999)",
	"MKD_displayName": "macedon dínár",
	"GWP_displayName": "Guinea-Bissaui peso",
	"CNY_displayName": "Kínai jüan renminbi",
	"MAF_displayName": "Marokkói frank",
	"JOD_displayName": "jordániai dínár",
	"OMR_displayName": "ománi rial",
	"BOV_displayName": "Bolíviai mvdol",
	"XPT_displayName": "platina",
	"AUD_symbol": "AUD",
	"NOK_displayName": "norvég korona",
	"SCR_displayName": "seychelle-szigeteki rúpia",
	"XBA_displayName": "Európai kompozit egység",
	"CSK_displayName": "Csehszlovák kemény korona",
	"PLZ_displayName": "Lengyel zloty (1950–1995)",
	"UAK_displayName": "Ukrán karbovanec",
	"MGF_displayName": "Madagaszkári frank",
	"GNS_displayName": "Guineai syli",
	"YUN_displayName": "Jugoszláv konvertibilis dínár",
	"GYD_displayName": "guyanai dollár",
	"QAR_displayName": "katari rial",
	"ALL_displayName": "albán lek",
	"BBD_displayName": "barbadosi dollár",
	"SSP_displayName": "dél-szudáni font",
	"RON_displayName": "román lej",
	"XCD_symbol": "XCD",
	"AMD_displayName": "örmény dram",
	"CYP_displayName": "Ciprusi font",
	"GBP_symbol": "GBP",
	"SEK_displayName": "svéd korona",
	"MMK_displayName": "mianmari kyat",
	"ZAR_displayName": "dél-afrikai rand",
	"ECV_displayName": "Ecuadori Unidad de Valor Constante (UVC)",
	"AWG_displayName": "arubai florin",
	"STD_displayName": "São Tomé és Príncipe-i dobra",
	"CAD_displayName": "kanadai dollár",
	"ADP_displayName": "Andorrai peseta",
	"MRO_displayName": "mauritániai ouguiya",
	"ESB_displayName": "spanyol peseta (konvertibilis kontó)",
	"LSL_displayName": "Lesothoi loti",
	"TND_displayName": "tunéziai dínár",
	"USD_symbol": "$",
	"BRC_displayName": "Brazi cruzado (1986–1989)",
	"BMD_displayName": "bermudai dollár",
	"BRL_displayName": "brazil real",
	"JMD_displayName": "jamaicai dollár",
	"SOS_displayName": "szomáli shilling",
	"SAR_displayName": "szaúdi riyal",
	"PEI_displayName": "Perui inti",
	"ESP_displayName": "Spanyol peseta",
	"HKD_displayName": "hongkongi dollár",
	"BWP_displayName": "botswanai pula",
	"TTD_displayName": "Trinidad és Tobago-i dollár",
	"BSD_displayName": "bahamai dollár",
	"BIF_displayName": "burundi frank",
	"FRF_displayName": "Francia frank",
	"DKK_displayName": "dán korona",
	"AED_displayName": "EAE-dirham",
	"AOK_displayName": "Angolai kwanza (1977–1990)",
	"ATS_displayName": "Osztrák schilling",
	"PEN_displayName": "perui sol nuevo",
	"CRC_displayName": "Costa Rica-i colon",
	"PAB_displayName": "panamai balboa",
	"CHE_displayName": "WIR euro",
	"GQE_displayName": "Egyenlítői-guineai ekwele guineana",
	"DZD_displayName": "algériai dínár",
	"EEK_displayName": "Észt korona",
	"YDD_displayName": "Jemeni dínár",
	"GHC_displayName": "Ghánai cedi (1979–2007)",
	"MXP_displayName": "Mexikói ezüst peso (1861–1992)",
	"XPD_displayName": "palládium",
	"XAG_displayName": "Ezüst",
	"AFN_displayName": "afgán afghani",
	"XFO_displayName": "Francia arany frank",
	"GWE_displayName": "Portugál guinea escudo",
	"BOB_displayName": "bolíviai boliviano",
	"CAD_symbol": "CAD",
	"VND_displayName": "vietnami dong",
	"AFA_displayName": "afgán afghani (1927–2002)",
	"ZWD_displayName": "Zimbabwei dollár (1980–2008)",
	"JPY_symbol": "¥",
	"SRD_displayName": "suriname-i dollár",
	"ZRN_displayName": "Zairei új zaire",
	"XAU_displayName": "Arany",
	"KRW_symbol": "KRW",
	"BOP_displayName": "Bolíviai peso",
	"XBD_displayName": "Európai kontó egység (XBD)",
	"TZS_displayName": "tanzániai shilling",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "román lej (1952–2006)",
	"LRD_displayName": "libériai dollár",
	"KRW_displayName": "dél-koreai won",
	"SHP_displayName": "Szent Ilona-i font",
	"MZE_displayName": "Mozambik escudo",
	"MZN_displayName": "mozambiki metikális",
	"SDD_displayName": "Szudáni dínár (1992–2007)",
	"HRK_displayName": "horvát kuna",
	"FKP_displayName": "falkland-szigeteki font",
	"COP_displayName": "kolumbiai peso",
	"YUD_displayName": "Jugoszláv kemény dínár",
	"YUM_displayName": "Jugoszláv új dínár",
	"THB_displayName": "thai baht",
	"UZS_displayName": "üzbegisztáni szum",
	"MGA_displayName": "madagaszkári ariary",
	"COU_displayName": "Unidad de Valor Real",
	"TWD_displayName": "tajvani új dollár",
	"UGS_displayName": "Ugandai shilling (1966–1987)",
	"ZAL_displayName": "Dél-afrikai rand (pénzügyi)",
	"GEL_displayName": "grúz lari",
	"ILP_displayName": "Izraeli font",
	"DDM_displayName": "Kelet-Német márka",
	"KES_displayName": "kenyai shilling",
	"CUC_displayName": "kubai konvertibilis peso",
	"CZK_displayName": "cseh korona",
	"UGX_displayName": "ugandai shilling",
	"ILS_symbol": "ILS",
	"TMT_displayName": "türkmenisztáni manat",
	"THB_symbol": "THB",
	"BGL_displayName": "Bolgár kemény leva",
	"ARP_displayName": "Argentín peso (1983–1985)",
	"RUR_displayName": "orosz rubel (1991–1998)",
	"ERN_displayName": "eritreai nakfa",
	"ESA_displayName": "spanyol peseta (A–kontó)",
	"CLF_displayName": "Chilei unidades de fomento",
	"BRB_displayName": "Brazi cruzeiro novo (1967–1986)",
	"BHD_displayName": "bahreini dinár",
	"SYP_displayName": "szíriai font",
	"SZL_displayName": "szváziföldi lilangeni",
	"INR_displayName": "indiai rúpia",
	"PTE_displayName": "Portugál escudo",
	"KPW_displayName": "észak-koreai won",
	"XOF_displayName": "CFA frank BCEAO",
	"MXN_displayName": "mexikói peso",
	"RWF_displayName": "ruandai frank",
	"ETB_displayName": "etiópiai birr",
	"LTL_displayName": "litvániai litas",
	"BND_displayName": "brunei dollár",
	"SUR_displayName": "Szovjet rubel",
	"SKK_displayName": "Szlovák korona",
	"AOA_displayName": "angolai kwanza",
	"CVE_displayName": "Cape Verde-i escudo",
	"BRL_symbol": "BRL",
	"XTS_displayName": "Tesztelési pénznemkód",
	"CLP_displayName": "chilei peso",
	"HUF_displayName": "magyar forint",
	"TJS_displayName": "tádzsikisztáni somoni",
	"GBP_displayName": "brit font sterling",
	"TPE_displayName": "Timori escudo",
	"BDT_displayName": "bangladesi taka",
	"SGD_displayName": "szingapúri dollár",
	"SLL_displayName": "Sierra Leone-i leone",
	"XAF_displayName": "CFA frank BEAC",
	"MTL_displayName": "Máltai líra",
	"KHR_displayName": "kambodzsai riel",
	"ZRZ_displayName": "Zairei zaire",
	"RSD_displayName": "szerb dínár",
	"BEC_displayName": "Belga frank (konvertibilis)",
	"BEL_displayName": "Belga frank (pénzügyi)",
	"AZN_displayName": "azerbajdzsáni manat",
	"FIM_displayName": "Finn markka",
	"ZWL_displayName": "Zimbabwei dollár (2009)",
	"PKR_displayName": "pakisztáni rúpia",
	"UYP_displayName": "Uruguay-i peso (1975–1993)",
	"CHW_displayName": "WIR frank",
	"ZMW_displayName": "zambiai kwacha",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "lengyel zloty",
	"UAH_displayName": "ukrán hrivnya",
	"BTN_displayName": "bhutáni ngultrum",
	"YER_displayName": "jemeni rial",
	"UYU_displayName": "uruguay-i peso",
	"CSD_displayName": "szerb dinár",
	"VEF_displayName": "venezuelai bolivar",
	"PGK_displayName": "pápua új-guineai kina",
	"XBC_displayName": "Európai kontó egység (XBC)",
	"EUR_displayName": "euró",
	"MUR_displayName": "mauritiusi rúpia",
	"MAD_displayName": "marokkói dirham",
	"SDG_displayName": "szudáni font",
	"BYR_displayName": "fehérorosz rubel",
	"VEB_displayName": "Venezuelai bolivar (1871–2008)",
	"IQD_displayName": "iraki dínár",
	"MZM_displayName": "Mozambik metical",
	"NZD_symbol": "NZD",
	"SIT_displayName": "Szlovén tolar",
	"XCD_displayName": "kelet-karibi dollár",
	"RUB_displayName": "orosz rubel",
	"BUK_displayName": "Burmai kyat",
	"ILS_displayName": "izraeli új sékel",
	"INR_symbol": "INR",
	"NAD_displayName": "namíbiai dollár",
	"HNL_displayName": "hodurasi lempira",
	"GTQ_displayName": "guatemalai quetzal",
	"GEK_displayName": "Grúz kupon larit",
	"EUR_symbol": "EUR",
	"NZD_displayName": "új-zélandi dollár",
	"ARA_displayName": "Argentín austral",
	"ARS_displayName": "argentin peso",
	"ANG_displayName": "holland antilláki forint"
}
//end v1.x content
);