define(
//begin v1.x content
{
	"KHR_displayName": "Riel cambojano",
	"FJD_displayName": "Dólar de Fiji",
	"KPW_displayName": "Won norte-coreano",
	"XCD_displayName": "Dólar das Caraíbas Orientais",
	"HUF_displayName": "Forint húngaro",
	"IQD_displayName": "Dinar iraquiano",
	"EGP_displayName": "Libra egípcia",
	"TTD_displayName": "Dólar de Trindade e Tobago",
	"GHS_displayName": "Cedi de Gana",
	"BRL_symbol": "R$",
	"NIC_displayName": "Córdoba nicaraguano",
	"BTN_displayName": "Ngultrum do Butão",
	"TWD_symbol": "NT$",
	"CZK_displayName": "Coroa checa",
	"SBD_displayName": "Dólar das Ilhas Salomão",
	"NOK_displayName": "Coroa norueguesa",
	"MNT_displayName": "Tugrik da Mongólia",
	"INR_displayName": "Rupia indiana",
	"KRW_displayName": "Won sul-coreano",
	"BMD_displayName": "Dólar bermudense",
	"BDT_displayName": "Taka de Bangladesh",
	"KGS_displayName": "Som do Quirguistão",
	"DJF_displayName": "Franco jibutiano",
	"ANG_displayName": "Florim das Antilhas Holandesas",
	"USD_displayName": "Dólar dos Estados Unidos",
	"TMT_displayName": "Manat do Turcomenistão",
	"HTG_displayName": "Gourde haitiano",
	"XCD_symbol": "EC$",
	"BWP_displayName": "Pula de Botswana",
	"HKD_symbol": "HK$",
	"RSD_displayName": "Dinar sérvio",
	"SSP_displayName": "Libra sul-sudanesa",
	"DKK_displayName": "Coroa dinamarquesa",
	"PAB_displayName": "Balboa panamenho",
	"XAF_symbol": "FCFA",
	"AWG_displayName": "Florim de Aruba",
	"ILS_symbol": "₪",
	"NAD_displayName": "Dólar da Namíbia",
	"UGX_displayName": "Xelim ugandense",
	"MXV_displayName": "Unidad de Inversion (UDI) mexicana",
	"ZMW_displayName": "Kwacha zambiano",
	"HNL_displayName": "Lempira das Honduras",
	"BHD_displayName": "Dinar baremita",
	"VEF_displayName": "Bolívar venezuelano",
	"BIF_displayName": "Franco burundiano",
	"MKD_displayName": "Dinar macedónio",
	"USD_symbol": "US$",
	"SRD_displayName": "Dólar do Suriname",
	"XAF_displayName": "Franco CFA de BEAC",
	"XOF_displayName": "Franco CFA de BCEAO",
	"LTL_displayName": "Litas da Lituânia",
	"BAD_displayName": "Dinar da Bósnia-Herzegóvina",
	"GYD_displayName": "Dólar da Guiana",
	"COP_displayName": "Peso colombiano",
	"MMK_displayName": "Kyat de Mianmar",
	"MVR_displayName": "Rupia das Ilhas Maldivas",
	"SAR_displayName": "Rial saudita",
	"AFA_displayName": "Afeghani (1927–2002)",
	"XPF_symbol": "CFPF",
	"CHF_displayName": "Franco suíço",
	"PTE_group": ",",
	"STD_displayName": "Dobra de São Tomé e Príncipe",
	"IDR_displayName": "Rupia indonésia",
	"PYG_displayName": "Guarani paraguaio",
	"IRR_displayName": "Rial iraniano",
	"CNY_symbol": "CN¥",
	"UYU_displayName": "Peso uruguaio",
	"EUR_displayName": "Euro",
	"SDG_displayName": "Libra sudanesa",
	"SLL_displayName": "Leone de Serra Leoa",
	"LKR_displayName": "Rupia do Sri Lanka",
	"GMD_displayName": "Dalasi da Gâmbia",
	"SZL_displayName": "Lilangeni da Suazilândia",
	"GNF_displayName": "Franco Guineense",
	"SCR_displayName": "Rupia seichelense",
	"ALL_displayName": "Lek albanês",
	"GEL_displayName": "Lari georgiano",
	"AMD_displayName": "Dram arménio",
	"UZS_symbol": "UZS",
	"MXN_symbol": "MX$",
	"NZD_displayName": "Dólar neozelandês",
	"AFN_displayName": "Afegani do Afeganistão",
	"JMD_displayName": "Dólar jamaicano",
	"GTQ_displayName": "Quetzal da Guatemala",
	"LVL_displayName": "Lats da Letónia",
	"NIO_displayName": "Córdoba Ouro nicaraguano",
	"OMR_displayName": "Rial de Omã",
	"KMF_displayName": "Franco comoriano",
	"GBP_displayName": "Libra esterlina britânica",
	"AOA_displayName": "Kwanza angolano",
	"PTE_decimal": "$",
	"VUV_displayName": "Vatu de Vanuatu",
	"TOP_displayName": "Paʻanga de Tonga",
	"PTE_pattern": "#,##0.00 ¤",
	"GIP_displayName": "Libra de Gibraltar",
	"BYB_displayName": "Rublo novo bielorusso (1994–1999)",
	"BZD_displayName": "Dólar belizense",
	"MAD_displayName": "Dirham marroquino",
	"CLP_displayName": "Peso chileno",
	"SYP_displayName": "Libra síria",
	"NPR_displayName": "Rupia nepalesa",
	"UZS_displayName": "Som do Uzbequistão",
	"GBP_symbol": "£",
	"JOD_displayName": "Dinar jordaniano",
	"YER_displayName": "Rial iemenita",
	"BRL_displayName": "Real brasileiro",
	"TRY_displayName": "Lira turca",
	"CVE_displayName": "Escudo cabo-verdiano",
	"BSD_displayName": "Dólar das Bahamas",
	"THB_symbol": "฿",
	"LYD_displayName": "Dinar líbio",
	"BAM_displayName": "Marco bósnio-herzegóvino conversível",
	"NGN_displayName": "Naira nigeriana",
	"GMD_symbol": "GMD",
	"AUD_symbol": "AU$",
	"WST_displayName": "Tala samoano",
	"TND_displayName": "Dinar tunisino",
	"LRD_displayName": "Dólar liberiano",
	"ILS_displayName": "Sheqel novo israelita",
	"KZT_displayName": "Tenge do Cazaquistão",
	"CUC_displayName": "Peso cubano conversível",
	"BGN_displayName": "Lev búlgaro",
	"MXN_displayName": "Peso mexicano",
	"CUP_displayName": "Peso cubano",
	"BYR_displayName": "Rublo bielorusso",
	"XOF_symbol": "CFA",
	"NZD_symbol": "NZ$",
	"UAH_displayName": "Hryvnia da Ucrânia",
	"BND_displayName": "Dólar bruneíno",
	"MUR_displayName": "Rupia mauriciana",
	"SEK_displayName": "Coroa sueca",
	"ETB_displayName": "Birr etíope",
	"ARS_displayName": "Peso argentino",
	"TWD_displayName": "Novo dólar taiwanês",
	"JPY_displayName": "Iene japonês",
	"MZN_displayName": "Metical de Moçambique",
	"TJS_displayName": "Somoni do Tajaquistão",
	"PEN_displayName": "Novo sol peruano",
	"XPF_displayName": "Franco CFP",
	"VND_symbol": "₫",
	"KWD_displayName": "Dinar kuwaitiano",
	"LAK_displayName": "Kip de Laos",
	"RON_displayName": "Leu romeno",
	"HRK_displayName": "Kuna croata",
	"BTN_symbol": "BTN",
	"THB_displayName": "Baht da Tailândia",
	"PLN_displayName": "Zloti polaco",
	"DZD_displayName": "Dinar argelino",
	"AZN_displayName": "Manat do Azerbaijão",
	"PGK_displayName": "Kina da Papua-Nova Guiné",
	"LBP_displayName": "Libra libanesa",
	"KRW_symbol": "₩",
	"RWF_displayName": "Franco ruandês",
	"SHP_displayName": "Libra de Santa Helena",
	"BEC_displayName": "Franco belga (convertível)",
	"TZS_displayName": "Xelim tanzaniano",
	"MGA_displayName": "Ariari de Madagáscar",
	"ERN_displayName": "Nakfa da Eritreia",
	"MDL_displayName": "Leu moldavo",
	"PHP_displayName": "Peso filipino",
	"AED_displayName": "Dirham dos Emirados Árabes Unidos",
	"BOB_displayName": "Boliviano",
	"KYD_displayName": "Dólar das Ilhas Caimão",
	"BBD_displayName": "Dólar barbadense",
	"XXX_displayName": "Moeda desconhecida",
	"CAD_displayName": "Dólar canadiano",
	"INR_symbol": "₹",
	"DOP_displayName": "Peso dominicano",
	"MRO_displayName": "Ouguiya da Mauritânia",
	"ZMK_displayName": "Kwacha zambiano (1968–2012)",
	"CAD_symbol": "CA$",
	"ECV_displayName": "Unidad de Valor Constante (UVC) do Equador",
	"RUB_displayName": "Rublo russo",
	"QAR_displayName": "Rial do Qatar",
	"MOP_displayName": "Pataca de Macau",
	"SOS_displayName": "Xelim somali",
	"CYP_displayName": "Libra de Chipre",
	"MWK_displayName": "Kwacha do Malawi",
	"SGD_displayName": "Dólar de Singapura",
	"KES_displayName": "Xelim queniano",
	"CRC_displayName": "Colon costa-riquenho",
	"JPY_symbol": "JP¥",
	"ZAR_displayName": "Rand sul-africano",
	"AUD_displayName": "Dólar australiano",
	"PKR_displayName": "Rupia paquistanesa",
	"EUR_symbol": "€",
	"VND_displayName": "Dong vietnamita",
	"HKD_displayName": "Dólar de Hong Kong",
	"MXP_displayName": "Peso Plata mexicano (1861–1992)",
	"MYR_displayName": "Ringgit malaio",
	"CNY_displayName": "Yuan chinês",
	"CDF_displayName": "Franco congolês",
	"ISK_displayName": "Coroa islandesa",
	"FKP_displayName": "Libra das Ilhas Falkland"
}
//end v1.x content
);