define(
//begin v1.x content
{
	"BRE_displayName": "Бразилски крузеиро (1990–1993)",
	"DEM_displayName": "Немачка марка",
	"CUP_displayName": "Кубански пезо",
	"PYG_displayName": "Парагвајски гуарни",
	"MDL_displayName": "Молдавски леј",
	"DOP_displayName": "Доминикански пезо",
	"NGN_displayName": "Нигеријска наира",
	"KZT_displayName": "Казахстански тенџ",
	"MXV_displayName": "Мексички унидад де инверсион (UDI)",
	"LTT_displayName": "Литвански талонас",
	"LAK_displayName": "Лаошки кип",
	"LKR_displayName": "Шриланканскa рупиja",
	"AOR_displayName": "Анголијска кванза реађустадо (1995–1999)",
	"XEU_displayName": "Европска валутна јединица",
	"XOF_symbol": "CFA",
	"USS_displayName": "САД долар (исти дан)",
	"MNT_displayName": "Монголски тугрик",
	"RHD_displayName": "Родејскидолар",
	"MOP_displayName": "Маканишка патака",
	"TJR_displayName": "Таџихистанска рубља",
	"LUC_displayName": "Луксембуршки конвертибилни франак",
	"LUL_displayName": "Луксембуршки финансијски франак",
	"AON_displayName": "Анголијска нова кванза (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "Белгијски франак",
	"GHS_displayName": "Гански цеди",
	"IEP_displayName": "Ирска фунта",
	"SBD_displayName": "Соломонско-острвски долар",
	"TRY_symbol": "Тл",
	"GRD_displayName": "Грчка драхма",
	"NIC_displayName": "Никарагванска кордоба",
	"AZM_displayName": "Азербејџански манат (1993–2006)",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "Малтешка фунта",
	"LVR_displayName": "Латвијска рубља",
	"GNF_displayName": "Гвинејски франак",
	"GIP_displayName": "Гибралтарска фунта",
	"SRG_displayName": "Суринамски гилдер",
	"BAD_displayName": "Босанско-Херцеговачки динар",
	"FJD_displayName": "Фиџи долар",
	"BAM_displayName": "Конвертибилна марка",
	"XBB_displayName": "Европска новчана јединица",
	"CDF_displayName": "Конголски франак",
	"HRD_displayName": "Хрватски динар",
	"BZD_displayName": "Белизе долар",
	"MLF_displayName": "Малијански франак",
	"EGP_displayName": "Египатска фунта",
	"MVR_displayName": "Малдивска руфија",
	"TRY_displayName": "Турска лира",
	"ILR_displayName": "Стари израелски шекели",
	"SDP_displayName": "Стара суданска фунта",
	"XRE_displayName": "RINET фонд",
	"NPR_displayName": "Непалскa рупиja",
	"PHP_displayName": "Филипински пезо",
	"RSD_symbol": "дин.",
	"WST_displayName": "Самоанска тала",
	"TRL_displayName": "Турска лира (1922–2005)",
	"JPY_displayName": "Јапански јен",
	"TMM_displayName": "Туркменистански манат (1993–2009)",
	"BGN_displayName": "Бугарски лев",
	"KYD_displayName": "Кајманска острва долар",
	"VUV_displayName": "Вануатски вату",
	"IRR_displayName": "Ирански риjал",
	"DJF_displayName": "Џибутански франак",
	"XDR_displayName": "Посебна цртаћа права",
	"ECS_displayName": "Еквадорски сакр",
	"HKD_symbol": "HK$",
	"NLG_displayName": "Холандски гулден",
	"ISJ_displayName": "Стара исландска круна",
	"MWK_displayName": "Малавијска квача",
	"HTG_displayName": "Хаићански гурд",
	"PES_displayName": "Перуански сол",
	"LYD_displayName": "Либијски динар",
	"BRR_displayName": "Бразилски крузеиро",
	"XXX_displayName": "Непозната или неважећа валута",
	"IDR_displayName": "Индонежанска рупија",
	"USD_displayName": "Амерички долар",
	"KGS_displayName": "Киргистански сом",
	"BRN_displayName": "Бразилијски нови крузадо",
	"CHF_displayName": "Швајцарски франак",
	"ISK_displayName": "Исландска круна",
	"LUF_displayName": "Луксембуршки франак",
	"SVC_displayName": "Салвадорски колон",
	"ZMK_displayName": "Замбијска квача (1968–2012)",
	"ZWR_displayName": "Зимбабвеански долар (2008)",
	"TOP_displayName": "Тонгоншка Панга",
	"ITL_displayName": "Италијанска лира",
	"USN_displayName": "САД долар (следећи дан)",
	"VND_symbol": "₫",
	"KWD_displayName": "Кувајтски динар",
	"NIO_displayName": "Никарагванска златна кордоба",
	"KMF_displayName": "Коморски франак",
	"UYI_displayName": "Уругвајски пезо ен унидадес индексадас",
	"MYR_displayName": "Малезијски ринггит",
	"XFU_displayName": "Француски UIC-франак",
	"GMD_displayName": "Гамбијски даласи",
	"LVL_displayName": "Латвијски лати",
	"AUD_displayName": "Аустралијски долар",
	"XPF_displayName": "CFP франак",
	"LBP_displayName": "Либанска фунта",
	"BYB_displayName": "Белоруска нова рубља (1994–1999)",
	"MKD_displayName": "Македонски денар",
	"GWP_displayName": "Гвинеја Бисао Пезо",
	"CNY_displayName": "Кинески јуан ренминби",
	"MAF_displayName": "Марокански франак",
	"JOD_displayName": "Јордански динар",
	"OMR_displayName": "Омански ријал",
	"BOV_displayName": "Боливијски мвдол",
	"XPT_displayName": "Платина",
	"AUD_symbol": "A$",
	"NOK_displayName": "Норвешка круна",
	"SCR_displayName": "Сејшелска рупија",
	"XBA_displayName": "Европска композитна јединица",
	"CSK_displayName": "Чехословачка тврда круна",
	"PLZ_displayName": "Пољски злоти (1950–1995)",
	"UAK_displayName": "Украјински карбованети",
	"MGF_displayName": "Малагасијски франак",
	"GNS_displayName": "Гвинејски сили",
	"YUN_displayName": "Југословенски конвертибилни динар",
	"GYD_displayName": "Гујански долар",
	"QAR_displayName": "Катаршки ријал",
	"ALL_displayName": "Албански лек",
	"BBD_displayName": "Барбадошки долар",
	"SSP_displayName": "Јужносуданска фунта",
	"RON_displayName": "Румунски леј (1952–2006)",
	"AMD_displayName": "Јерменски драм",
	"CYP_displayName": "Кипарска фунта",
	"GBP_symbol": "£",
	"SEK_displayName": "Шведска круна",
	"MMK_displayName": "Мјанмарски кјат",
	"ZAR_displayName": "Јужно-афрички ранд",
	"ECV_displayName": "Еквадорски унидад де валор константе",
	"AWG_displayName": "Арубански флорин",
	"STD_displayName": "Сао Томе и Принципе добра",
	"CAD_displayName": "Канадски долар",
	"ADP_displayName": "Андорска пезета",
	"MRO_displayName": "Мауританијска oгија",
	"ESB_displayName": "Шпанска пезета (конвертибилнирачун)",
	"LSL_displayName": "Лесото лоти",
	"TND_displayName": "Tунежански динар",
	"BAM_symbol": "КМ",
	"BRC_displayName": "Бразилијски крузадо",
	"BMD_displayName": "Бермудски долар",
	"BRL_displayName": "Бразилски Реал",
	"JMD_displayName": "Јамајкански долар",
	"SOS_displayName": "Сомалијски шилинг",
	"SAR_displayName": "Саудијски ријал",
	"PEI_displayName": "Перуански инти",
	"ESP_displayName": "Шпанска пезета",
	"HKD_displayName": "Хонгконшки долар",
	"BWP_displayName": "Боцванска пула",
	"TTD_displayName": "Тринидад тобагошки долар",
	"BSD_displayName": "Бахамски долар",
	"BIF_displayName": "Бурундски франак",
	"FRF_displayName": "Француски франак",
	"DKK_displayName": "Данска круна",
	"AED_displayName": "Уједињени арапски емирати дирхам",
	"AOK_displayName": "Анголијска кванза (1977–1990)",
	"ATS_displayName": "Аустријски шилинг",
	"PEN_displayName": "Перуански нуево сол",
	"CRC_displayName": "Костарикански колон",
	"PAB_displayName": "Панамска балбоа",
	"CHE_displayName": "WIR евро",
	"GQE_displayName": "Екваторијално-гвинејски еквеле",
	"DZD_displayName": "Алжирски динар",
	"EEK_displayName": "Естонска кроон",
	"YDD_displayName": "Јеменски динар",
	"GHC_displayName": "Гански цеди (1979–2007)",
	"PLN_symbol": "зл",
	"MXP_displayName": "Мексички сребрни пезо (1861–1992)",
	"XPD_displayName": "Паладијум",
	"XAG_displayName": "Сребро",
	"AFN_displayName": "Авганистански авгани",
	"XFO_displayName": "Француски златни франак",
	"GWE_displayName": "Португалска гвинеја ескудо",
	"BOB_displayName": "Боливијски Боливиано",
	"VND_displayName": "Вијетнамски донг",
	"AFA_displayName": "Авганистански авгани (1927–2002)",
	"ZWD_displayName": "Зимбабвеански долар (1980–2008)",
	"JPY_symbol": "¥",
	"SRD_displayName": "Суринамски долар",
	"ZRN_displayName": "Заирски нови заир",
	"XAU_displayName": "Злато",
	"KRW_symbol": "₩",
	"BOP_displayName": "Боливијски пезо",
	"XBD_displayName": "Европска јединица рачуна (XBD)",
	"TZS_displayName": "Танзанијски шилинг",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "Румунски леј",
	"VNN_displayName": "Вијетнамски донг (1978–1985)",
	"LRD_displayName": "Либеријски долар",
	"KRW_displayName": "Јужнокорејски Вон",
	"SHP_displayName": "Св. јеленска фунта",
	"MZE_displayName": "Мозамбијски ескудо",
	"MZN_displayName": "Мозамбијски метикал",
	"SDD_displayName": "Стари судански динар",
	"HRK_displayName": "Хрватска куна",
	"FKP_displayName": "Фокландска острва фунта",
	"COP_displayName": "Колумбијски пезо",
	"YUD_displayName": "Југословенски тврди динар",
	"YUM_displayName": "Југословенски нови динар",
	"THB_displayName": "Таи бахт",
	"UZS_displayName": "Узбекистански сом",
	"MGA_displayName": "Малагасијски ариари",
	"COU_displayName": "Унидад де валоршки реал",
	"TWD_displayName": "Нови тајвански долар",
	"UGS_displayName": "Угандски шилинг (1966–1987)",
	"ZAL_displayName": "Јужно-афрички ранд (финансијски)",
	"GEL_displayName": "Грузијски лари",
	"ILP_displayName": "Израелска фунта",
	"DDM_displayName": "Источно-немачка марка",
	"KES_displayName": "Кенијски шилинг",
	"CUC_displayName": "Кубански конвертибилни песо",
	"CZK_displayName": "Чешка круна",
	"UGX_displayName": "Угандски шилинг",
	"ILS_symbol": "₪",
	"TMT_displayName": "Туркменистански манат",
	"THB_symbol": "฿",
	"BGL_displayName": "Бугарски тврди лев",
	"ARP_displayName": "Аргентински пезо (1983–1985)",
	"RUR_displayName": "Руска рубља (1991–1998)",
	"ERN_displayName": "Eритрејска накфa",
	"ESA_displayName": "Шпанска пезета (рачун)",
	"CLF_displayName": "Чилеовски унидадес се фоменто",
	"BRB_displayName": "Бразилски нови крузеиро (1967–1986)",
	"BHD_displayName": "Бахреински динар",
	"SYP_displayName": "Сиријска фунта",
	"SZL_displayName": "Свази лилангени",
	"INR_displayName": "Индијска рупија",
	"PTE_displayName": "Португалски ескудо",
	"KPW_displayName": "Севернокорејски вон",
	"XOF_displayName": "CFA франак BCEAO",
	"MXN_displayName": "Мексички пезо",
	"RWF_displayName": "Руандски франак",
	"ETB_displayName": "Етиопијски бир",
	"LTL_displayName": "Литвански литас",
	"BND_displayName": "Брунејски долар",
	"SUR_displayName": "Совјетска рубља",
	"SKK_displayName": "Словачка круна",
	"AOA_displayName": "Анголијска кванза",
	"CVE_displayName": "Зеленортски ескудо",
	"XTS_displayName": "Код тестиране валуте",
	"CLP_displayName": "Чилеански пезо",
	"HUF_displayName": "Мађарска форинта",
	"TJS_displayName": "Tаџихистански сомон",
	"GBP_displayName": "Британска фунта стерлинга",
	"TPE_displayName": "Тиморшки ескудо",
	"BDT_displayName": "Бангладешка така",
	"SGD_displayName": "Сингапурски долар",
	"SLL_displayName": "Сијера-леоншки леоне",
	"XAF_displayName": "CFA франак BEAC",
	"MTL_displayName": "Малтешка лира",
	"KHR_displayName": "Kамбоџански ријел",
	"ZRZ_displayName": "Заирски заир",
	"RSD_displayName": "Српски динар",
	"BEC_displayName": "Белгијски франак (конвертибилни)",
	"BEL_displayName": "Белгијски франак (финансијски)",
	"AZN_displayName": "Азербејџански манат",
	"FIM_displayName": "Финска марка",
	"ZWL_displayName": "Зимбабвеански долар (2009)",
	"PKR_displayName": "Пакистанскa рупиja",
	"UYP_displayName": "Уругвајски пезо (1975–1993)",
	"CHW_displayName": "WIR франак",
	"ZMW_displayName": "Замбијска квача",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "Пољски злот",
	"UAH_displayName": "Украјинска хривња",
	"BTN_displayName": "Бутански нгултрум",
	"YER_displayName": "Јеменски риjал",
	"UYU_displayName": "Уругвајски пезо",
	"CSD_displayName": "Стари српски динар",
	"VEF_displayName": "Венецуелански боливар",
	"PGK_displayName": "Папуанска кина",
	"XBC_displayName": "Европска јединица рачуна (XBC)",
	"EUR_displayName": "Евро",
	"MUR_displayName": "Маурицијска рупија",
	"MAD_displayName": "Марокански дирхам",
	"SDG_displayName": "Суданска фунта",
	"BYR_displayName": "Белоруска рубља",
	"VEB_displayName": "Венецуелански боливар (1871–2008)",
	"IQD_displayName": "Ирачки динар",
	"MZM_displayName": "Стари мозамбијски метикал",
	"SIT_displayName": "Словеначки толар",
	"CZK_symbol": "Кч",
	"XCD_displayName": "Источно-карипски долар",
	"RUB_displayName": "Руска рубља",
	"BUK_displayName": "Бурмански кјат",
	"ILS_displayName": "Израелски нови шекел",
	"INR_symbol": "₹",
	"NAD_displayName": "Намибијски долар",
	"HNL_displayName": "Хондурашка лемпира",
	"GTQ_displayName": "Гватемалски квецал",
	"GEK_displayName": "Грузијски купон ларит",
	"EUR_symbol": "€",
	"NZD_displayName": "Новозеландски долар",
	"ARA_displayName": "Аргентински аустрал",
	"ARS_displayName": "Аргентински пезо",
	"ANG_displayName": "Холандски антили гилдер"
}
//end v1.x content
);