define(
//begin v1.x content
{
	"BRE_displayName": "Brasiliansk cruzeiro (1990–1993)",
	"DEM_displayName": "Tysk mark",
	"CUP_displayName": "Cubansk peso",
	"PYG_displayName": "Paraguaysk guarani",
	"MDL_displayName": "Moldovisk leu",
	"DOP_displayName": "Dominikansk peso",
	"NGN_displayName": "Nigeriansk naira",
	"KZT_displayName": "Kasakhisk tenge",
	"LTT_displayName": "Litauisk talonas",
	"LAK_displayName": "Laotisk kip",
	"LKR_displayName": "Srilankansk rupee",
	"AOR_displayName": "Angolansk kwanza (1995–1999)",
	"XEU_displayName": "ECU",
	"XOF_symbol": "CFA",
	"USS_displayName": "Amerikansk dollar (samme dag)",
	"MNT_displayName": "Mongolsk tugrik",
	"MOP_displayName": "Macaosk pataca",
	"TJR_displayName": "Tadsjikisk rubel",
	"LUC_displayName": "Luxembourgsk konvertibel franc",
	"LUL_displayName": "Luxembourgsk finansiel franc",
	"AON_displayName": "Angolansk nye kwanza (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "Belgisk franc",
	"GHS_displayName": "Ghanesisk cedi",
	"IEP_displayName": "Irsk pund",
	"SBD_displayName": "Salomonsk dollar",
	"GRD_displayName": "Græsk drakme",
	"NIC_displayName": "Nicaraguansk cordoba (1988–1991)",
	"AZM_displayName": "Aserbajdsjansk manat (1993–2006)",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "Maltesisk pund",
	"LVR_displayName": "Lettisk rubel",
	"GNF_displayName": "Guineansk franc",
	"GIP_displayName": "Gibraltarisk pund",
	"SRG_displayName": "Surinamsk guilder",
	"BAD_displayName": "Bosnien-Hercegovinsk dinar",
	"FJD_displayName": "Fijiansk dollar",
	"BAM_displayName": "Bosnien-Hercegovinsk konvertibel mark",
	"XBB_displayName": "EMU",
	"CDF_displayName": "Congolesisk franc",
	"HRD_displayName": "Kroatisk dinar",
	"BZD_displayName": "Belizisk dollar",
	"MLF_displayName": "Malisk franc",
	"EGP_displayName": "Egyptisk pund",
	"MVR_displayName": "Maldivisk rufiyaa",
	"TRY_displayName": "Tyrkisk lira",
	"SDP_displayName": "Sudansk pund (1957–1998)",
	"XRE_displayName": "RINET-fond",
	"NPR_displayName": "Nepalesisk rupee",
	"PHP_displayName": "Filippinsk peso",
	"WST_displayName": "Samoansk tala",
	"TRL_displayName": "Tyrkisk lire (1922–2005)",
	"JPY_displayName": "Japansk yen",
	"TMM_displayName": "Turkmensk manat (1993–2009)",
	"BGN_displayName": "Bulgarsk lev",
	"KYD_displayName": "Caymansk dollar",
	"VUV_displayName": "Vanuaisk vatu",
	"IRR_displayName": "Iransk rial",
	"DJF_displayName": "Djiboutisk franc",
	"XDR_displayName": "SDR",
	"ECS_displayName": "Ecuadoriansk sucre",
	"HKD_symbol": "HK$",
	"NLG_displayName": "Hollandsk guilder",
	"MWK_displayName": "Malawisk kwacha",
	"HTG_displayName": "Haitisk gourde",
	"PES_displayName": "Peruviansk sol (1863–1965)",
	"LYD_displayName": "Libysk dinar",
	"BRR_displayName": "Brasiliansk cruzeiro (1993–1994)",
	"DKK_symbol": "kr",
	"XXX_displayName": "Ukendt valuta",
	"IDR_displayName": "Indonesisk pupiah",
	"USD_displayName": "Amerikansk dollar",
	"KGS_displayName": "Kirgisisk som",
	"BRN_displayName": "Brasiliansk cruzado novo (1989–1990)",
	"CHF_displayName": "Schweizisk franc",
	"ISK_displayName": "Islansk krone",
	"LUF_displayName": "Luxembourgsk franc",
	"MXN_symbol": "MX$",
	"SVC_displayName": "Salvadoransk colon",
	"ZMK_displayName": "Zambisk kwacha (1968–2012)",
	"ZWR_displayName": "Zimbabwisk dollar (2008)",
	"TOP_displayName": "Tongansk paʻanga",
	"ITL_displayName": "Italiensk lire",
	"USN_displayName": "Amerikansk dollar (næste dag)",
	"VND_symbol": "₫",
	"KWD_displayName": "Kuwaitisk dinar",
	"NIO_displayName": "Nicaraguansk cordoba",
	"KMF_displayName": "Comorisk franc",
	"MYR_displayName": "Malaysisk ringgit",
	"XFU_displayName": "Fransk UIC-franc",
	"GMD_displayName": "Gambisk dalasi",
	"LVL_displayName": "Lettisk lat",
	"AUD_displayName": "Australsk dollar",
	"XPF_displayName": "CFP-franc",
	"LBP_displayName": "Libanesisk pund",
	"BYB_displayName": "Hviderussisk rubel (1994–1999)",
	"MKD_displayName": "Makedonsk denar",
	"GWP_displayName": "Guineansk peso",
	"CNY_displayName": "Kinesisk yuan renminbi",
	"MAF_displayName": "Marokkansk franc",
	"JOD_displayName": "Jordansk dinar",
	"OMR_displayName": "Omansk rial",
	"BOV_displayName": "Boliviansk mvdol",
	"XPT_displayName": "Platin",
	"AUD_symbol": "AU$",
	"NOK_displayName": "Norsk krone",
	"SCR_displayName": "Seychellisk rupee",
	"XBA_displayName": "EURCO",
	"CSK_displayName": "Tjekkoslovakisk hard koruna",
	"PLZ_displayName": "Polsk zloty (1950–1995)",
	"UAK_displayName": "Ukrainsk karbovanetz",
	"MGF_displayName": "Madagaskisk franc",
	"GNS_displayName": "Guineansk syli",
	"YUN_displayName": "Jugoslavisk konvertibel dinar (1990–1992)",
	"GYD_displayName": "Guyansk dollar",
	"QAR_displayName": "Qatarsk rial",
	"ALL_displayName": "Albansk lek",
	"BBD_displayName": "Barbadisk dollar",
	"SSP_displayName": "Sydsudanske pund",
	"RON_displayName": "Rumænsk leu",
	"XCD_symbol": "EC$",
	"AMD_displayName": "Armensk dram",
	"CYP_displayName": "Cypriotisk pund",
	"GBP_symbol": "£",
	"SEK_displayName": "Svensk krone",
	"MMK_displayName": "Myanmarsk kyat",
	"ZAR_displayName": "Sydafrikansk rand",
	"AWG_displayName": "Arubansk florin",
	"STD_displayName": "Dobra fra Sao Tome og Principe",
	"CAD_displayName": "Canadisk dollar",
	"ADP_displayName": "Andorransk peseta",
	"MRO_displayName": "Mauritansk ouguiya",
	"ESB_displayName": "Spansk peseta (konvertibel konto)",
	"LSL_displayName": "Lesothisk loti",
	"TND_displayName": "Tunesisk dinar",
	"USD_symbol": "$",
	"BRC_displayName": "Brasiliansk cruzado (1986–1989)",
	"BMD_displayName": "Bermudansk dollar",
	"BRL_displayName": "Brasiliansk real",
	"JMD_displayName": "Jamaicansk dollar",
	"SOS_displayName": "Somalisk shilling",
	"SAR_displayName": "Saudiarabisk riyal",
	"PEI_displayName": "Peruviansk inti",
	"ESP_displayName": "Spansk peseta",
	"HKD_displayName": "Hongkong dollar",
	"BWP_displayName": "Botswansk pula",
	"TTD_displayName": "Dollar fra Trinidad og Tobago",
	"BSD_displayName": "Bahamansk dollar",
	"BIF_displayName": "Burundisk franc",
	"FRF_displayName": "Fransk franc",
	"DKK_displayName": "Dansk krone",
	"AED_displayName": "Dirham fra de Forenede Arabiske Emirater",
	"AOK_displayName": "Angolansk kwanza (1977–1990)",
	"ATS_displayName": "Østrigsk schilling",
	"PEN_displayName": "Peruviansk nuevo sol",
	"CRC_displayName": "Costaricansk colón",
	"PAB_displayName": "Panamansk balboa",
	"CHE_displayName": "WIR euro",
	"GQE_displayName": "Ækvatorialguineask ekwele",
	"DZD_displayName": "Algerisk dinar",
	"EEK_displayName": "Estisk kroon",
	"YDD_displayName": "Yemenitisk dinar",
	"GHC_displayName": "Ghanesisk cedi (1979–2007)",
	"MXP_displayName": "Mexicansk silver peso (1861–1992)",
	"XPD_displayName": "Palladium",
	"XAG_displayName": "Sølv",
	"AFN_displayName": "Afghansk afghani",
	"XFO_displayName": "Fransk guldfranc",
	"GWE_displayName": "Portugisisk guinea escudo",
	"BOB_displayName": "Boliviansk boliviano",
	"CAD_symbol": "CA$",
	"VND_displayName": "Vietnamesisk dong",
	"ZWD_displayName": "Zimbabwisk dollar (1980–2008)",
	"AFA_displayName": "Afghansk afghani (1927–2002)",
	"JPY_symbol": "JP¥",
	"SRD_displayName": "Surinamsk dollar",
	"ZRN_displayName": "Ny zairisk zaire (1993–1998)",
	"XAU_displayName": "Guld",
	"KRW_symbol": "₩",
	"BOP_displayName": "Boliviansk peso",
	"TZS_displayName": "Tanzanisk shilling",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "Rumænsk leu (1952–2006)",
	"LRD_displayName": "Liberisk dollar",
	"KRW_displayName": "Sydkoreansk won",
	"SHP_displayName": "Pund fra Saint Helena",
	"MZE_displayName": "Mozambiquisk escudo",
	"MZN_displayName": "Mozambiquisk metical",
	"SDD_displayName": "Sudansk dinar (1992–2007)",
	"HRK_displayName": "Kroatisk kuna",
	"FKP_displayName": "Pund fra Falklandsøerne",
	"COP_displayName": "Colombiansk peso",
	"YUD_displayName": "Jugoslavisk hard dinar (1966–1990)",
	"YUM_displayName": "Jugoslavisk noviy dinar (1994–2002)",
	"THB_displayName": "Thailandsk baht",
	"UZS_displayName": "Usbekisk sum",
	"MGA_displayName": "Madagaskisk ariary",
	"TWD_displayName": "Ny taiwansk dollar",
	"UGS_displayName": "Ugandisk shilling (1966–1987)",
	"ZAL_displayName": "Sydafrikansk rand (financial)",
	"GEL_displayName": "Georgisk lari",
	"ILP_displayName": "Israelsk pund",
	"DDM_displayName": "Østtysk mark",
	"KES_displayName": "Kenyansk shilling",
	"CUC_displayName": "Cubansk konvertibel peso",
	"CZK_displayName": "Tjekkisk koruna",
	"UGX_displayName": "Ugandisk shilling",
	"ILS_symbol": "₪",
	"TMT_displayName": "Turkmensk manat",
	"THB_symbol": "฿",
	"BGL_displayName": "Bulgarsk hard lev",
	"ARP_displayName": "Argentinsk peso (1983–1985)",
	"RUR_displayName": "Russisk rubel (1991–1998)",
	"ERN_displayName": "Eritreisk nakfa",
	"ESA_displayName": "Spansk peseta (A–konto)",
	"BRB_displayName": "Brasiliansk cruzeiro novo (1967–1986)",
	"BHD_displayName": "Bahrainsk dinar",
	"SYP_displayName": "Syrisk pund",
	"SZL_displayName": "Swazilandsk lilangeni",
	"INR_displayName": "Indisk rupee",
	"PTE_displayName": "Portugisisk escudo",
	"KPW_displayName": "Nordkoreansk won",
	"XOF_displayName": "CFA-franc BCEAO",
	"MXN_displayName": "Mexicansk peso",
	"RWF_displayName": "Rwandisk franc",
	"ETB_displayName": "Etiopisk birr",
	"LTL_displayName": "Litauisk litas",
	"BND_displayName": "Bruneisk dollar",
	"SUR_displayName": "Sovjetisk rubel",
	"SKK_displayName": "Slovakisk koruna",
	"AOA_displayName": "Angolansk kwanza",
	"CVE_displayName": "Kapverdisk escudo",
	"BRL_symbol": "R$",
	"XTS_displayName": "testvalutakode",
	"CLP_displayName": "Chilensk peso",
	"HUF_displayName": "Ungarsk forint",
	"TJS_displayName": "Tadsjikisk somoni",
	"GBP_displayName": "Britisk pund",
	"TPE_displayName": "Escudo fra Timor",
	"BDT_displayName": "Bangladeshisk taka",
	"SGD_displayName": "Singaporeansk dollar",
	"SLL_displayName": "Sierraleonsk leone",
	"XAF_displayName": "CFA-franc (BEAC)",
	"MTL_displayName": "Maltesisk lira",
	"ZRZ_displayName": "Zairisk zaire (1971–1993)",
	"KHR_displayName": "Cambodjansk riel",
	"RSD_displayName": "Serbisk dinar",
	"BEC_displayName": "Belgisk franc (konvertibel)",
	"BEL_displayName": "Belgisk franc (financial)",
	"AZN_displayName": "Aserbajdsjansk manat",
	"FIM_displayName": "Finsk mark",
	"ZWL_displayName": "Zimbabwisk dollar (2009)",
	"PKR_displayName": "Pakistansk rupee",
	"UYP_displayName": "Uruguayansk peso (1975–1993)",
	"ZMW_displayName": "Zambisk kwacha",
	"CHW_displayName": "WIR franc",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "Polsk zloty",
	"UAH_displayName": "Ukrainsk grynia",
	"BTN_displayName": "Bhutansk ngultrum",
	"YER_displayName": "Yemenitisk rial",
	"UYU_displayName": "Uruguayansk peso",
	"CSD_displayName": "Serbisk dinar (2002–2006)",
	"VEF_displayName": "Venezuelansk bolivar",
	"PGK_displayName": "Papuansk kina",
	"EUR_displayName": "Euro",
	"MUR_displayName": "Mauritisk rupee",
	"MAD_displayName": "Marokkansk dirham",
	"SDG_displayName": "Sudansk pund",
	"BYR_displayName": "Hviderussisk rubel",
	"VEB_displayName": "Venezuelansk bolivar (1871–2008)",
	"IQD_displayName": "Irakisk dinar",
	"MZM_displayName": "Mozambiquisk metical (1980–2006)",
	"NZD_symbol": "NZ$",
	"SIT_displayName": "Slovensk tolar",
	"XCD_displayName": "Østkaribisk dollar",
	"RUB_displayName": "Russisk rubel",
	"BUK_displayName": "Burmesisk kyat",
	"ILS_displayName": "Ny israelsk shekel",
	"INR_symbol": "₹",
	"NAD_displayName": "Namibisk dollar",
	"HNL_displayName": "Honduransk lempira",
	"GTQ_displayName": "Guatemalansk quetzal",
	"GEK_displayName": "Georgisk kupon larit",
	"EUR_symbol": "€",
	"NZD_displayName": "New Zealandsk dollar",
	"ARA_displayName": "Argentinsk austral",
	"ARS_displayName": "Argentinsk peso",
	"ANG_displayName": "Nederlandske Antiller-gylden"
}
//end v1.x content
);