define(
//begin v1.x content
{
	"BRE_displayName": "cruceiro brasileño (1990–1993)",
	"DEM_displayName": "marco alemán",
	"CUP_displayName": "peso cubano",
	"PYG_displayName": "guaraní paraguayo",
	"MDL_displayName": "leu moldavo",
	"DOP_displayName": "peso dominicano",
	"NGN_displayName": "naira nigeriano",
	"KZT_displayName": "tenge kazako",
	"MXV_displayName": "unidad de inversión (UDI) mexicana",
	"LTT_displayName": "talonas lituano",
	"LAK_displayName": "kip laosiano",
	"LKR_displayName": "rupia de Sri Lanka",
	"AOR_displayName": "kwanza reajustado angoleño (1995–1999)",
	"XEU_displayName": "unidad de moneda europea",
	"XOF_symbol": "XOF",
	"USS_displayName": "dólar estadounidense (mismo día)",
	"MNT_displayName": "tugrik mongol",
	"RHD_displayName": "dólar rodesiano",
	"MOP_displayName": "pataca de Macao",
	"TJR_displayName": "rublo tayiko",
	"LUC_displayName": "franco convertible luxemburgués",
	"LUL_displayName": "franco financiero luxemburgués",
	"AON_displayName": "nuevo kwanza angoleño (1990–2000)",
	"TWD_symbol": "TWD",
	"BEF_displayName": "franco belga",
	"GHS_displayName": "cedi ghanés",
	"IEP_displayName": "libra irlandesa",
	"SBD_displayName": "dólar de las Islas Salomón",
	"GRD_displayName": "dracma griego",
	"NIC_displayName": "córdoba nicaragüense (1988–1991)",
	"AZM_displayName": "manat azerí (1993–2006)",
	"CNY_symbol": "CNY",
	"MTP_displayName": "libra maltesa",
	"ARS_symbol": "AR$",
	"LVR_displayName": "rublo letón",
	"GNF_displayName": "franco guineano",
	"GIP_displayName": "libra de Gibraltar",
	"SRG_displayName": "florín surinamés",
	"BAD_displayName": "dinar bosnio",
	"FJD_displayName": "dólar de las Islas Fiyi",
	"BAM_displayName": "marco convertible de Bosnia-Herzegovina",
	"XBB_displayName": "unidad monetaria europea",
	"CDF_displayName": "franco congoleño",
	"HRD_displayName": "dinar croata",
	"BZD_displayName": "dólar de Belice",
	"MLF_displayName": "franco malí",
	"EGP_displayName": "libra egipcia",
	"MVR_displayName": "rufiyaa de Maldivas",
	"TRY_displayName": "lira turca",
	"SDP_displayName": "libra sudanesa antigua",
	"XRE_displayName": "fondos RINET",
	"NPR_displayName": "rupia nepalesa",
	"PHP_displayName": "peso filipino",
	"WST_displayName": "tala samoano",
	"TRL_displayName": "lira turca (1922–2005)",
	"JPY_displayName": "yen japonés",
	"TMM_displayName": "manat turcomano (1993–2009)",
	"BGN_displayName": "lev búlgaro",
	"KYD_displayName": "dólar de las Islas Caimán",
	"VUV_displayName": "vatu vanuatuense",
	"IRR_displayName": "rial iraní",
	"DJF_displayName": "franco de Yibuti",
	"XDR_displayName": "derechos especiales de giro",
	"ECS_displayName": "sucre ecuatoriano",
	"HKD_symbol": "HKD",
	"NLG_displayName": "florín neerlandés",
	"MWK_displayName": "kwacha de Malawi",
	"HTG_displayName": "gourde haitiano",
	"PES_displayName": "sol peruano",
	"LYD_displayName": "dinar libio",
	"BRR_displayName": "cruceiro brasileño",
	"XXX_displayName": "divisa desconocida",
	"IDR_displayName": "rupia indonesia",
	"USD_displayName": "dólar estadounidense",
	"KGS_displayName": "som kirguís",
	"BRN_displayName": "nuevo cruzado brasileño",
	"CHF_displayName": "franco suizo",
	"ISK_displayName": "corona islandesa",
	"LUF_displayName": "franco luxemburgués",
	"MXN_symbol": "MX$",
	"SVC_displayName": "colón salvadoreño",
	"ZMK_displayName": "kwacha zambiano (1968–2012)",
	"TOP_displayName": "paʻanga tongano",
	"ITL_displayName": "lira italiana",
	"USN_displayName": "dólar estadounidense (día siguiente)",
	"KWD_displayName": "dinar kuwaití",
	"NIO_displayName": "córdoba nicaragüense",
	"KMF_displayName": "franco comorense",
	"UYI_displayName": "peso uruguayo en unidades indexadas",
	"MYR_displayName": "ringgit malasio",
	"XFU_displayName": "franco UIC francés",
	"GMD_displayName": "dalasi gambiano",
	"LVL_displayName": "lats letón",
	"AUD_displayName": "dólar australiano",
	"XPF_displayName": "franco CFP",
	"LBP_displayName": "libra libanesa",
	"BYB_displayName": "nuevo rublo bielorruso (1994–1999)",
	"MKD_displayName": "dinar macedonio",
	"GWP_displayName": "peso de Guinea-Bissáu",
	"CNY_displayName": "yuan chino",
	"MAF_displayName": "franco marroquí",
	"JOD_displayName": "dinar jordano",
	"OMR_displayName": "rial omaní",
	"BOV_displayName": "MVDOL boliviano",
	"XPT_displayName": "platino",
	"AUD_symbol": "AU$",
	"NOK_displayName": "corona noruega",
	"SCR_displayName": "rupia de Seychelles",
	"XBA_displayName": "unidad compuesta europea",
	"CSK_displayName": "corona fuerte checoslovaca",
	"PLZ_displayName": "zloty polaco (1950–1995)",
	"UAK_displayName": "karbovanet ucraniano",
	"MGF_displayName": "franco malgache",
	"GNS_displayName": "syli guineano",
	"YUN_displayName": "dinar convertible yugoslavo",
	"GYD_displayName": "dólar guyanés",
	"QAR_displayName": "riyal de Qatar",
	"ALL_displayName": "lek albanés",
	"BBD_displayName": "dólar de Barbados",
	"SSP_displayName": "libra sursudanesa",
	"RON_displayName": "leu rumano",
	"XCD_symbol": "EC$",
	"AMD_displayName": "dram armenio",
	"CYP_displayName": "libra chipriota",
	"GBP_symbol": "GBP",
	"SEK_displayName": "corona sueca",
	"MMK_displayName": "kyat de Myanmar",
	"ZAR_displayName": "rand sudafricano",
	"ECV_displayName": "unidad de valor constante (UVC) ecuatoriana",
	"AWG_displayName": "florín de Aruba",
	"STD_displayName": "dobra de Santo Tomé y Príncipe",
	"CAD_displayName": "dólar canadiense",
	"ADP_displayName": "peseta andorrana",
	"MRO_displayName": "ouguiya mauritano",
	"ESB_displayName": "peseta española (cuenta convertible)",
	"LSL_displayName": "loti lesothense",
	"TND_displayName": "dinar tunecino",
	"USD_symbol": "$",
	"BRC_displayName": "cruzado brasileño",
	"BMD_displayName": "dólar de Bermudas",
	"BRL_displayName": "real brasileño",
	"JMD_displayName": "dólar de Jamaica",
	"SOS_displayName": "chelín somalí",
	"SAR_displayName": "riyal saudí",
	"PEI_displayName": "inti peruano",
	"ESP_displayName": "peseta española",
	"HKD_displayName": "dólar de Hong Kong",
	"ESP_symbol": "₧",
	"BWP_displayName": "pula botsuano",
	"TTD_displayName": "dólar de Trinidad y Tobago",
	"BSD_displayName": "dólar de las Bahamas",
	"BIF_displayName": "franco de Burundi",
	"FRF_displayName": "franco francés",
	"DKK_displayName": "corona danesa",
	"AED_displayName": "dírham de los Emiratos Árabes Unidos",
	"AOK_displayName": "kwanza angoleño (1977–1990)",
	"ATS_displayName": "chelín austriaco",
	"PEN_displayName": "nuevo sol peruano",
	"CRC_displayName": "colón costarricense",
	"PAB_displayName": "balboa panameño",
	"CHE_displayName": "euro WIR",
	"GQE_displayName": "ekuele de Guinea Ecuatorial",
	"DZD_displayName": "dinar argelino",
	"EEK_displayName": "corona estonia",
	"YDD_displayName": "dinar yemení",
	"GHC_displayName": "cedi ghanés (1979–2007)",
	"MXP_displayName": "peso de plata mexicano (1861–1992)",
	"XPD_displayName": "paladio",
	"XAG_displayName": "plata",
	"AFN_displayName": "afgani afgano",
	"XFO_displayName": "franco oro francés",
	"GWE_displayName": "escudo de Guinea Portuguesa",
	"BOB_displayName": "boliviano",
	"CAD_symbol": "CA$",
	"VND_displayName": "dong vietnamita",
	"AFA_displayName": "afgani (1927–2002)",
	"ZWD_displayName": "dólar de Zimbabue",
	"JPY_symbol": "JPY",
	"SRD_displayName": "dólar surinamés",
	"ZRN_displayName": "nuevo zaire zaireño",
	"XAU_displayName": "oro",
	"KRW_symbol": "KRW",
	"BOP_displayName": "peso boliviano",
	"XBD_displayName": "unidad de cuenta europea (XBD)",
	"TZS_displayName": "chelín tanzano",
	"XPF_symbol": "XPF",
	"ROL_displayName": "antiguo leu rumano",
	"LRD_displayName": "dólar liberiano",
	"KRW_displayName": "won surcoreano",
	"SHP_displayName": "libra de Santa Elena",
	"MZE_displayName": "escudo mozambiqueño",
	"MZN_displayName": "metical mozambiqueño",
	"SDD_displayName": "dinar sudanés",
	"HRK_displayName": "kuna croata",
	"FKP_displayName": "libra de las Islas Malvinas",
	"COP_displayName": "peso colombiano",
	"YUD_displayName": "dinar fuerte yugoslavo",
	"YUM_displayName": "super dinar yugoslavo",
	"THB_displayName": "baht tailandés",
	"UZS_displayName": "som uzbeko",
	"MGA_displayName": "ariary malgache",
	"COU_displayName": "unidad de valor real colombiana",
	"TWD_displayName": "nuevo dólar taiwanés",
	"UGS_displayName": "chelín ugandés (1966–1987)",
	"ZAL_displayName": "rand sudafricano (financiero)",
	"GEL_displayName": "lari georgiano",
	"ILP_displayName": "libra israelí",
	"DDM_displayName": "ostmark de Alemania del Este",
	"KES_displayName": "chelín keniata",
	"CUC_displayName": "peso cubano convertible",
	"CZK_displayName": "corona checa",
	"UGX_displayName": "chelín ugandés",
	"ILS_symbol": "ILS",
	"TMT_displayName": "manat turcomano",
	"BGL_displayName": "lev fuerte búlgaro",
	"ARP_displayName": "peso argentino (1983–1985)",
	"RUR_displayName": "rublo ruso (1991–1998)",
	"ERN_displayName": "nakfa eritreo",
	"ESA_displayName": "peseta española (cuenta A)",
	"CLF_displayName": "unidad de fomento chilena",
	"BRB_displayName": "nuevo cruceiro brasileño (1967–1986)",
	"BHD_displayName": "dinar bahreiní",
	"SYP_displayName": "libra siria",
	"SZL_displayName": "lilangeni suazi",
	"INR_displayName": "rupia india",
	"PTE_displayName": "escudo portugués",
	"KPW_displayName": "won norcoreano",
	"XOF_displayName": "franco CFA BCEAO",
	"MXN_displayName": "peso mexicano",
	"RWF_displayName": "franco ruandés",
	"ETB_displayName": "birr etíope",
	"LTL_displayName": "litas lituano",
	"BND_displayName": "dólar de Brunéi",
	"SUR_displayName": "rublo soviético",
	"SKK_displayName": "corona eslovaca",
	"AOA_displayName": "kwanza angoleño",
	"CVE_displayName": "escudo de Cabo Verde",
	"XTS_displayName": "código reservado para pruebas",
	"CLP_displayName": "peso chileno",
	"HUF_displayName": "florín húngaro",
	"TJS_displayName": "somoni tayiko",
	"GBP_displayName": "libra esterlina británica",
	"TPE_displayName": "escudo timorense",
	"BDT_displayName": "taka de Bangladesh",
	"SGD_displayName": "dólar singapurense",
	"SLL_displayName": "leone de Sierra Leona",
	"XAF_displayName": "franco CFA BEAC",
	"MTL_displayName": "lira maltesa",
	"KHR_displayName": "riel camboyano",
	"ZRZ_displayName": "zaire zaireño",
	"RSD_displayName": "dinar serbio",
	"BEC_displayName": "franco belga (convertible)",
	"BEL_displayName": "franco belga (financiero)",
	"AZN_displayName": "manat azerí",
	"FIM_displayName": "marco finlandés",
	"ZWL_displayName": "dólar zimbabuense",
	"PKR_displayName": "rupia pakistaní",
	"UYP_displayName": "peso uruguayo (1975–1993)",
	"ZMW_displayName": "kwacha zambiano",
	"CHW_displayName": "franco WIR",
	"PLN_displayName": "zloty polaco",
	"UAH_displayName": "grivna ucraniana",
	"BTN_displayName": "ngultrum butanés",
	"YER_displayName": "rial yemení",
	"UYU_displayName": "peso uruguayo",
	"CSD_displayName": "antiguo dinar serbio",
	"VEF_displayName": "bolívar venezolano",
	"PGK_displayName": "kina de Papúa Nueva Guinea",
	"XBC_displayName": "unidad de cuenta europea (XBC)",
	"EUR_displayName": "euro",
	"MUR_displayName": "rupia mauriciana",
	"MAD_displayName": "dírham marroquí",
	"SDG_displayName": "libra sudanesa",
	"BYR_displayName": "rublo bielorruso",
	"VEB_displayName": "bolívar venezolano (1871–2008)",
	"IQD_displayName": "dinar iraquí",
	"MZM_displayName": "antiguo metical mozambiqueño",
	"SIT_displayName": "tólar esloveno",
	"XCD_displayName": "dólar del Caribe Oriental",
	"RUB_displayName": "rublo ruso",
	"BUK_displayName": "kyat birmano",
	"ILS_displayName": "nuevo sheqel israelí",
	"INR_symbol": "INR",
	"NAD_displayName": "dólar de Namibia",
	"HNL_displayName": "lempira hondureño",
	"GTQ_displayName": "quetzal guatemalteco",
	"GEK_displayName": "kupon larit georgiano",
	"NZD_displayName": "dólar neozelandés",
	"ARA_displayName": "austral argentino",
	"ARS_displayName": "peso argentino",
	"ANG_displayName": "florín de las Antillas Neerlandesas"
}
//end v1.x content
);