define(
//begin v1.x content
{
	"BRE_displayName": "Бразильский крузейро (1990–1993)",
	"DEM_displayName": "Немецкая марка",
	"CUP_displayName": "Кубинское песо",
	"TMT_symbol": "ТМТ",
	"PYG_displayName": "Парагвайский гуарани",
	"MDL_displayName": "Молдавский лей",
	"DOP_displayName": "Доминиканское песо",
	"NGN_displayName": "Нигерийская найра",
	"KZT_displayName": "Казахский тенге",
	"MXV_displayName": "Мексиканская пересчетная единица (UDI)",
	"LTT_displayName": "Литовский талон",
	"LAK_displayName": "Кип ЛНДР",
	"LKR_displayName": "Шри-Ланкийская рупия",
	"AOR_displayName": "Ангольская кванза реюстадо (1995–1999)",
	"XEU_displayName": "ЭКЮ (единица европейской валюты)",
	"XOF_symbol": "CFA",
	"USS_displayName": "Доллар США текущего дня",
	"MNT_displayName": "Монгольский тугрик",
	"RHD_displayName": "Родезийский доллар",
	"MOP_displayName": "Патака Макао",
	"TJR_displayName": "Таджикский рубль",
	"LUC_displayName": "Конвертируемый франк Люксембурга",
	"LUL_displayName": "Финансовый франк Люксембурга",
	"AON_displayName": "Ангольская новая кванза (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "Бельгийский франк",
	"GHS_displayName": "Ганский седи",
	"IEP_displayName": "Ирландский фунт",
	"SBD_displayName": "Доллар Соломоновых островов",
	"GRD_displayName": "Греческая драхма",
	"NIC_displayName": "Никарагуанская кордоба (1988–1991)",
	"AZM_displayName": "Старый азербайджанский манат",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "Мальтийский фунт",
	"LVR_displayName": "Латвийский рубль",
	"GNF_displayName": "Гвинейский франк",
	"GIP_displayName": "Гибралтарский фунт",
	"SRG_displayName": "Суринамский гульден",
	"BAD_displayName": "Динар Боснии и Герцеговины",
	"FJD_displayName": "Доллар Фиджи",
	"BAM_displayName": "Конвертируемая марка Боснии и Герцеговины",
	"XBB_displayName": "Европейская денежная единица",
	"CDF_displayName": "Конголезский франк",
	"HRD_displayName": "Хорватский динар",
	"BZD_displayName": "Белизский доллар",
	"MLF_displayName": "Малийский франк",
	"EGP_displayName": "Египетский фунт",
	"MVR_displayName": "Мальдивская руфия",
	"TRY_displayName": "Турецкая лира",
	"SDP_displayName": "Старый суданский фунт",
	"XRE_displayName": "единица RINET-фондов",
	"NPR_displayName": "Непальская рупия",
	"PHP_displayName": "Филиппинское песо",
	"WST_displayName": "Тала Самоа",
	"TRL_displayName": "Турецкая лира (1922–2005)",
	"JPY_displayName": "Японская иена",
	"TMM_displayName": "Туркменский манат",
	"BGN_displayName": "Болгарский лев",
	"KYD_displayName": "Доллар Каймановых островов",
	"VUV_displayName": "Вату",
	"IRR_displayName": "Иранский риал",
	"DJF_displayName": "Франк Джибути",
	"XDR_displayName": "СДР (специальные права заимствования)",
	"ECS_displayName": "Эквадорский сукре",
	"HKD_symbol": "HK$",
	"NLG_displayName": "Нидерландский гульден",
	"MWK_displayName": "Малавийская квача",
	"HTG_displayName": "Гаитянский гурд",
	"PES_displayName": "Перуанский соль",
	"LYD_displayName": "Ливийский динар",
	"BRR_displayName": "Бразильский крузейро",
	"XXX_displayName": "Неизвестная или недействительная валюта",
	"IDR_displayName": "Индонезийская рупия",
	"USD_displayName": "Доллар США",
	"KGS_displayName": "Киргизский сом",
	"BRN_displayName": "Бразильское новое крузадо",
	"CHF_displayName": "Швейцарский франк",
	"ISK_displayName": "Исландская крона",
	"LUF_displayName": "Люксембургский франк",
	"MXN_symbol": "MX$",
	"SVC_displayName": "Сальвадорский колон",
	"ZMK_displayName": "Квача (замбийская) (1968–2012)",
	"TOP_displayName": "Паанга",
	"ITL_displayName": "Итальянская лира",
	"USN_displayName": "Доллар США следующего дня",
	"VND_symbol": "₫",
	"KWD_displayName": "Кувейтский динар",
	"NIO_displayName": "Никарагуанская кордоба",
	"KMF_displayName": "Франк Коморских островов",
	"UYI_displayName": "Уругвайский песо (индекс инфляции)",
	"MYR_displayName": "Малайзийский ринггит",
	"XFU_displayName": "Французский UIC-франк",
	"XXX_symbol": "XXXX",
	"GMD_displayName": "Гамбийский даласи",
	"LVL_displayName": "Латвийский лат",
	"AUD_displayName": "Австралийский доллар",
	"XPF_displayName": "Франк КФП",
	"LBP_displayName": "Ливанский фунт",
	"BYB_displayName": "Белорусский рубль (1994–1999)",
	"MKD_displayName": "Македонский динар",
	"GWP_displayName": "Песо Гвинеи-Бисау",
	"CNY_displayName": "Юань Ренминби",
	"MAF_displayName": "Марокканский франк",
	"JOD_displayName": "Иорданский динар",
	"OMR_displayName": "Оманский риал",
	"BOV_displayName": "Боливийский мвдол",
	"XPT_displayName": "Платина",
	"AUD_symbol": "A$",
	"NOK_displayName": "Норвежская крона",
	"SCR_displayName": "Сейшельская рупия",
	"XBA_displayName": "Европейская составная единица",
	"CSK_displayName": "Чехословацкая твердая крона",
	"PLZ_displayName": "Злотый",
	"UAK_displayName": "Карбованец (украинский)",
	"MGF_displayName": "Малагасийский франк",
	"GNS_displayName": "Гвинейская сили",
	"YUN_displayName": "Югославский динар",
	"GYD_displayName": "Гайанский доллар",
	"QAR_displayName": "Катарский риал",
	"ALL_displayName": "Албанский лек",
	"BBD_displayName": "Барбадосский доллар",
	"SSP_displayName": "Южносуданский фунт",
	"RON_displayName": "Румынский лей",
	"XCD_symbol": "EC$",
	"AMD_displayName": "Армянский драм",
	"CYP_displayName": "Кипрский фунт",
	"GBP_symbol": "£",
	"SEK_displayName": "Шведская крона",
	"MMK_displayName": "Кьят",
	"ZAR_displayName": "Южноафриканский рэнд",
	"ECV_displayName": "Постоянная единица стоимости Эквадора",
	"AWG_displayName": "Арубанский флорин",
	"STD_displayName": "Добра Сант-Томе и Принсипи",
	"CAD_displayName": "Канадский доллар",
	"ADP_displayName": "Андоррская песета",
	"MRO_displayName": "Мавританская угия",
	"ESB_displayName": "Испанская песета (конвертируемая)",
	"LSL_displayName": "Лоти",
	"TND_displayName": "Тунисский динар",
	"USD_symbol": "$",
	"BRC_displayName": "Бразильское крузадо",
	"BMD_displayName": "Бермудский доллар",
	"BRL_displayName": "Бразильский реал",
	"JMD_displayName": "Ямайский доллар",
	"SOS_displayName": "Сомалийский шиллинг",
	"SAR_displayName": "Саудовский риал",
	"PEI_displayName": "Перуанское инти",
	"ESP_displayName": "Испанская песета",
	"HKD_displayName": "Гонконгский доллар",
	"BWP_displayName": "Ботсванская пула",
	"TTD_displayName": "Доллар Тринидада и Тобаго",
	"BSD_displayName": "Багамский доллар",
	"BIF_displayName": "Бурундийский франк",
	"FRF_displayName": "Французский франк",
	"DKK_displayName": "Датская крона",
	"AED_displayName": "Дирхам (ОАЭ)",
	"AOK_displayName": "Ангольская кванза (1977–1990)",
	"ATS_displayName": "Австрийский шиллинг",
	"PEN_displayName": "Перуанский новый соль",
	"CRC_displayName": "Костариканский колон",
	"PAB_displayName": "Панамское бальбоа",
	"CHE_displayName": "WIR евро",
	"GQE_displayName": "Эквеле экваториальной Гвинеи",
	"DZD_displayName": "Алжирский динар",
	"EEK_displayName": "Эстонская крона",
	"YDD_displayName": "Йеменский динар",
	"GHC_displayName": "Ганский седи (1979–2007)",
	"MXP_displayName": "Мексиканское серебряное песо (1861–1992)",
	"XPD_displayName": "Палладий",
	"XAG_displayName": "Серебро",
	"AFN_displayName": "Афганский афгани",
	"XFO_displayName": "Французский золотой франк",
	"GWE_displayName": "Эскудо Португальской Гвинеи",
	"BOB_displayName": "Боливийский боливиано",
	"CAD_symbol": "CA$",
	"VND_displayName": "Вьетнамский донг",
	"AFA_displayName": "Афгани (1927–2002)",
	"ZWD_displayName": "Доллар Зимбабве",
	"JPY_symbol": "¥",
	"SRD_displayName": "Суринамский доллар",
	"ZRN_displayName": "Новый заир",
	"XAU_displayName": "Золото",
	"KRW_symbol": "₩",
	"BOP_displayName": "Боливийское песо",
	"XBD_displayName": "расчетная единица европейского валютного соглашения (XBD)",
	"TZS_displayName": "Танзанийский шиллинг",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "Старый Румынский лей",
	"LRD_displayName": "Либерийский доллар",
	"KRW_displayName": "Вона Республики Кореи",
	"SHP_displayName": "Фунт острова Святой Елены",
	"MZE_displayName": "Мозамбикское эскудо",
	"MZN_displayName": "Мозамбикский метикал",
	"SDD_displayName": "Суданский динар",
	"HRK_displayName": "Хорватская куна",
	"FKP_displayName": "Фунт Фолклендских островов",
	"COP_displayName": "Колумбийское песо",
	"YUD_displayName": "Югославский твердый динар",
	"YUM_displayName": "Югославский новый динар",
	"THB_displayName": "Таиландский бат",
	"UZS_displayName": "Узбекский сум",
	"MGA_displayName": "Малагасийский ариари",
	"COU_displayName": "Единица реальной стоимости Колумбии",
	"TWD_displayName": "Новый тайваньский доллар",
	"UGS_displayName": "Старый угандийский шиллинг",
	"ZAL_displayName": "Южноафриканский рэнд (финансовый)",
	"GEL_displayName": "Грузинский лари",
	"ILP_displayName": "Израильский фунт",
	"DDM_displayName": "Восточногерманская марка",
	"KES_displayName": "Кенийский шиллинг",
	"CUC_displayName": "Кубинское конвертируемое песо",
	"CZK_displayName": "Чешская крона",
	"UGX_displayName": "Угандийский шиллинг",
	"ILS_symbol": "₪",
	"TMT_displayName": "Туркменский новый манат",
	"THB_symbol": "฿",
	"BGL_displayName": "Лев",
	"ARP_displayName": "Аргентинское песо (1983–1985)",
	"RUR_displayName": "Российский рубль (1991–1998)",
	"ERN_displayName": "Накфа",
	"ESA_displayName": "Испанская песета (А)",
	"CLF_displayName": "Условная расчетная единица Чили",
	"BRB_displayName": "Бразильский новый крузейро (1967–1986)",
	"BHD_displayName": "Бахрейнский динар",
	"SYP_displayName": "Сирийский фунт",
	"SZL_displayName": "Свазилендский лилангени",
	"INR_displayName": "Индийская рупия",
	"PTE_displayName": "Португальское эскудо",
	"KPW_displayName": "Северо-корейская вона",
	"XOF_displayName": "Франк КФА ВСЕАО",
	"MXN_displayName": "Мексиканское новое песо",
	"RUB_symbol": "руб.",
	"RWF_displayName": "Франк Руанды",
	"ETB_displayName": "Эфиопский быр",
	"LTL_displayName": "Литовский лит",
	"BND_displayName": "Брунейский доллар",
	"SUR_displayName": "Рубль СССР",
	"SKK_displayName": "Словацкая крона",
	"AOA_displayName": "Ангольская кванза",
	"CVE_displayName": "Эскудо Кабо-Верде",
	"BRL_symbol": "R$",
	"XTS_displayName": "тестовый валютный код",
	"CLP_displayName": "Чилийское песо",
	"HUF_displayName": "Венгерский форинт",
	"TJS_displayName": "Таджикский сомони",
	"GBP_displayName": "Английский фунт стерлингов",
	"TPE_displayName": "Тиморское эскудо",
	"BDT_displayName": "Бангладешская така",
	"SGD_displayName": "Сингапурский доллар",
	"SLL_displayName": "Леоне",
	"XAF_displayName": "Франк КФА ВЕАС",
	"MTL_displayName": "Мальтийская лира",
	"KHR_displayName": "Камбоджийский риель",
	"ZRZ_displayName": "Заир",
	"RSD_displayName": "Сербский динар",
	"UAH_symbol": "₴",
	"BEC_displayName": "Бельгийский франк (конвертируемый)",
	"BEL_displayName": "Бельгийский франк (финансовый)",
	"AZN_displayName": "Азербайджанский манат",
	"FIM_displayName": "Финская марка",
	"ZWL_displayName": "Доллар Зимбабве (2009)",
	"PKR_displayName": "Пакистанская рупия",
	"UYP_displayName": "Уругвайское старое песо (1975–1993)",
	"CHW_displayName": "WIR франк",
	"ZMW_displayName": "Квача (замбийская)",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "Польский злотый",
	"UAH_displayName": "Украинская гривна",
	"BTN_displayName": "Бутанский нгултрум",
	"YER_displayName": "Йеменский риал",
	"UYU_displayName": "Уругвайское песо",
	"CSD_displayName": "Старый Сербский динар",
	"VEF_displayName": "Венесуэльский боливар",
	"PGK_displayName": "Кина",
	"XBC_displayName": "расчетная единица европейского валютного соглашения (XBC)",
	"RUR_symbol": "р.",
	"EUR_displayName": "Евро",
	"MUR_displayName": "Маврикийская рупия",
	"MAD_displayName": "Марокканский дирхам",
	"SDG_displayName": "Суданский фунт",
	"BYR_displayName": "Белорусский рубль",
	"VEB_displayName": "Венесуэльский боливар (1871–2008)",
	"IQD_displayName": "Иракский динар",
	"MZM_displayName": "Старый мозамбикский метикал",
	"NZD_symbol": "NZ$",
	"SIT_displayName": "Словенский толар",
	"XCD_displayName": "Восточно-карибский доллар",
	"RUB_displayName": "Российский рубль",
	"BUK_displayName": "Джа",
	"ILS_displayName": "Новый израильский шекель",
	"INR_symbol": "₹",
	"NAD_displayName": "Доллар Намибии",
	"HNL_displayName": "Гондурасская лемпира",
	"GTQ_displayName": "Гватемальский кетсаль",
	"GEK_displayName": "Грузинский купон",
	"EUR_symbol": "€",
	"NZD_displayName": "Новозеландский доллар",
	"ARA_displayName": "Аргентинский аустрал",
	"ARS_displayName": "Аргентинское песо",
	"ANG_displayName": "Нидерландский антильский гульден"
}
//end v1.x content
);