define({ root:

//begin v1.x content
{
	"dayPeriods-format-abbr@localeAlias212": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	},
	"dateTimeFormats-appendItem-Year": "{1} {0}",
	"field-tue-relative+-1": "last Tuesday",
	"field-year": "Year",
	"dateFormatItem-Hm": "HH:mm",
	"field-wed-relative+0": "this Wednesday",
	"field-wed-relative+1": "next Wednesday",
	"dateFormatItem-ms": "mm:ss",
	"timeFormat-short": "HH:mm",
	"field-minute": "Minute",
	"dateTimeFormat-short": "{1} {0}",
	"eraNarrow@localeAlias214": {
		"bundle": "generic",
		"target": "eraAbbr"
	},
	"field-day-relative+0": "today",
	"field-day-relative+1": "tomorrow",
	"timeFormat@localeAlias215": {
		"bundle": "gregorian",
		"target": "timeFormat"
	},
	"field-tue-relative+0": "this Tuesday",
	"field-tue-relative+1": "next Tuesday",
	"dayPeriods-format-narrow-am": "a",
	"dateFormatItem-MMMd": "MMM d",
	"dayPeriods-format-abbr-am": "AM",
	"field-week-relative+0": "this week",
	"field-month-relative+0": "this month",
	"field-week-relative+1": "next week",
	"field-month-relative+1": "next month",
	"timeFormat-medium": "HH:mm:ss",
	"field-second-relative+0": "now",
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
	"dateFormatItem-yyyyQQQ": "G y QQQ",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"eraNames": [
		"ERA0",
		"ERA1"
	],
	"dateFormatItem-GyMMMEd": "G y MMM d, E",
	"dateFormatItem-yyyyMd": "GGGGG y-MM-dd",
	"field-day": "Day",
	"field-year-relative+-1": "last year",
	"dayPeriods-format-wide-am": "AM",
	"dateFormatItem-yyyyMEd": "GGGGG y-MM-dd, E",
	"field-wed-relative+-1": "last Wednesday",
	"dayPeriods@localeAlias210": {
		"bundle": "gregorian",
		"target": "dayPeriods"
	},
	"dateTimeFormat-medium": "{1} {0}",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"field-second": "Second",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormat-long": "G y MMMM d",
	"dateFormatItem-GyMMMd": "G y MMM d",
	"quarters-standAlone-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"W",
		"T",
		"F",
		"S"
	],
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-mon-relative+-1": "last Monday",
	"dateFormatItem-GyMMM": "G y MMM",
	"field-month": "Month",
	"dateFormatItem-MMM": "LLL",
	"field-dayperiod": "Dayperiod",
	"days-format-short@localeAlias196": {
		"bundle": "gregorian",
		"target": "days-format-abbr"
	},
	"days-format-short@localeAlias197": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"months-standAlone-wide@localeAlias192": {
		"bundle": "generic",
		"target": "months-format-wide"
	},
	"dayPeriods-format-narrow-pm": "p",
	"dateFormat-medium": "G y MMM d",
	"eraAbbr": [
		"ERA0",
		"ERA1"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dayPeriods-format-abbr-pm": "PM",
	"dateFormatItem-yyyyM": "GGGGG y-MM",
	"months-standAlone-abbr@localeAlias190": {
		"bundle": "generic",
		"target": "months-format-abbr"
	},
	"months-standAlone-abbr@localeAlias191": {
		"bundle": "generic",
		"target": "months-format-wide"
	},
	"field-mon-relative+0": "this Monday",
	"field-mon-relative+1": "next Monday",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormatItem-yyyyMMMd": "G y MMM d",
	"days-format-short": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dayPeriods-format-wide-pm": "PM",
	"field-sat-relative+-1": "last Saturday",
	"eraNames@localeAlias213": {
		"bundle": "generic",
		"target": "eraAbbr"
	},
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-Md": "MM-dd",
	"field-hour": "Hour",
	"months-format-wide": [
		"M01",
		"M02",
		"M03",
		"M04",
		"M05",
		"M06",
		"M07",
		"M08",
		"M09",
		"M10",
		"M11",
		"M12"
	],
	"dateFormat-full": "G y MMMM d, EEEE",
	"field-month-relative+-1": "last month",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-fri-relative+0": "this Friday",
	"field-fri-relative+1": "next Friday",
	"dayPeriods-format-narrow-noon": "n",
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
	"field-week-relative+-1": "last week",
	"dateFormatItem-Ehm": "E h:mm a",
	"months-format-abbr": [
		"M01",
		"M02",
		"M03",
		"M04",
		"M05",
		"M06",
		"M07",
		"M08",
		"M09",
		"M10",
		"M11",
		"M12"
	],
	"timeFormat-long": "HH:mm:ss z",
	"days-standAlone-wide@localeAlias203": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"dateFormat-short": "GGGGG y-MM-dd",
	"quarters-format-narrow@localeAlias206": {
		"bundle": "gregorian",
		"target": "quarters-standAlone-narrow"
	},
	"days-standAlone-wide": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateFormatItem-yyyyMMMEd": "G y MMM d, E",
	"quarters@localeAlias204": {
		"bundle": "gregorian",
		"target": "quarters"
	},
	"dateTimeFormats-appendItem-Era": "{1} {0}",
	"days-format-narrow@localeAlias195": {
		"bundle": "gregorian",
		"target": "days-standAlone-narrow"
	},
	"dateFormatItem-H": "HH",
	"dateFormatItem-yyyy": "G y",
	"dateFormatItem-M": "L",
	"months-standAlone-wide": [
		"M01",
		"M02",
		"M03",
		"M04",
		"M05",
		"M06",
		"M07",
		"M08",
		"M09",
		"M10",
		"M11",
		"M12"
	],
	"field-sun-relative+-1": "last Sunday",
	"days-standAlone-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hm": "h:mm a",
	"days@localeAlias193": {
		"bundle": "gregorian",
		"target": "days"
	},
	"dateFormatItem-d": "d",
	"field-weekday": "Day of the Week",
	"field-sat-relative+0": "this Saturday",
	"dateFormatItem-h": "h a",
	"field-sat-relative+1": "next Saturday",
	"months-standAlone-abbr": [
		"M01",
		"M02",
		"M03",
		"M04",
		"M05",
		"M06",
		"M07",
		"M08",
		"M09",
		"M10",
		"M11",
		"M12"
	],
	"timeFormat-full": "HH:mm:ss zzzz",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateFormatItem-y": "G y",
	"field-thu-relative+0": "this Thursday",
	"field-thu-relative+1": "next Thursday",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
	"dayPeriods-format-abbr-noon": "noon",
	"quarters-standAlone-wide@localeAlias209": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
	"field-thu-relative+-1": "last Thursday",
	"field-week": "Week",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dateFormatItem-Ed": "d, E",
	"dateFormatItem-yyyyMMM": "G y MMM",
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
	"days-standAlone-short": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"days-standAlone-abbr@localeAlias198": {
		"bundle": "gregorian",
		"target": "days-format-abbr"
	},
	"days-standAlone-abbr@localeAlias199": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"dateFormatItem-yyyyQQQQ": "G y QQQQ",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"field-year-relative+0": "this year",
	"field-year-relative+1": "next year",
	"field-fri-relative+-1": "last Friday",
	"eraNarrow": [
		"ERA0",
		"ERA1"
	],
	"dayPeriods-format-wide-noon": "noon",
	"quarters-standAlone-abbr@localeAlias207": {
		"bundle": "gregorian",
		"target": "quarters-format-abbr"
	},
	"quarters-standAlone-abbr@localeAlias208": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"days-format-wide": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
	"dateFormatItem-EHm": "E HH:mm",
	"field-zone": "Zone",
	"days-format-abbr@localeAlias194": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"months-format-abbr@localeAlias188": {
		"bundle": "generic",
		"target": "months-format-wide"
	},
	"dateFormatItem-MMMEd": "MMM d, E",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"field-day-relative+-1": "yesterday",
	"quarters-format-abbr@localeAlias205": {
		"bundle": "gregorian",
		"target": "quarters-format-wide"
	},
	"days-format-abbr": [
		"Sun",
		"Mon",
		"Tue",
		"Wed",
		"Thu",
		"Fri",
		"Sat"
	],
	"field-sun-relative+0": "this Sunday",
	"months-format-narrow@localeAlias189": {
		"bundle": "generic",
		"target": "months-standAlone-narrow"
	},
	"field-sun-relative+1": "next Sunday",
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
	"dateFormatItem-Gy": "G y",
	"field-era": "Era",
	"days-standAlone-short@localeAlias200": {
		"bundle": "gregorian",
		"target": "days-format-short"
	},
	"days-standAlone-short@localeAlias201": {
		"bundle": "gregorian",
		"target": "days-format-abbr"
	},
	"days-standAlone-short@localeAlias202": {
		"bundle": "gregorian",
		"target": "days-format-wide"
	},
	"dayPeriods-format-abbr@localeAlias211": {
		"bundle": "gregorian",
		"target": "dayPeriods-format-wide"
	}
}
//end v1.x content
,
	"af": true,
	"agq": true,
	"ak": true,
	"am": true,
	"ar": true,
	"ar-dz": true,
	"ar-ma": true,
	"ar-tn": true,
	"as": true,
	"asa": true,
	"ast": true,
	"az": true,
	"az-cyrl": true,
	"bas": true,
	"be": true,
	"bem": true,
	"bez": true,
	"bg": true,
	"bm": true,
	"bn": true,
	"bo": true,
	"brx": true,
	"bs": true,
	"bs-cyrl": true,
	"ca": true,
	"cgg": true,
	"chr": true,
	"cs": true,
	"cy": true,
	"da": true,
	"dav": true,
	"de": true,
	"de-at": true,
	"dje": true,
	"dua": true,
	"dyo": true,
	"dz": true,
	"ebu": true,
	"ee": true,
	"el": true,
	"en": true,
	"en-150": true,
	"en-au": true,
	"en-be": true,
	"en-bw": true,
	"en-bz": true,
	"en-ca": true,
	"en-gb": true,
	"en-hk": true,
	"en-ie": true,
	"en-in": true,
	"en-mt": true,
	"en-nz": true,
	"en-pk": true,
	"en-sg": true,
	"en-za": true,
	"en-zw": true,
	"eo": true,
	"es": true,
	"es-419": true,
	"es-ar": true,
	"es-cl": true,
	"es-co": true,
	"es-gt": true,
	"es-hn": true,
	"es-mx": true,
	"es-pa": true,
	"es-pe": true,
	"es-pr": true,
	"es-us": true,
	"et": true,
	"eu": true,
	"ewo": true,
	"fa": true,
	"ff": true,
	"fi": true,
	"fil": true,
	"fo": true,
	"fr": true,
	"fr-be": true,
	"fr-ca": true,
	"fr-ch": true,
	"fur": true,
	"fy": true,
	"ga": true,
	"gd": true,
	"gl": true,
	"gsw": true,
	"gu": true,
	"guz": true,
	"ha": true,
	"haw": true,
	"he": true,
	"hi": true,
	"hr": true,
	"hu": true,
	"hy": true,
	"id": true,
	"ig": true,
	"is": true,
	"it": true,
	"it-ch": true,
	"ja": true,
	"jgo": true,
	"jmc": true,
	"ka": true,
	"kab": true,
	"kam": true,
	"kde": true,
	"kea": true,
	"khq": true,
	"ki": true,
	"kk": true,
	"kkj": true,
	"kl": true,
	"kln": true,
	"km": true,
	"kn": true,
	"ko": true,
	"ks": true,
	"ksb": true,
	"ksf": true,
	"ksh": true,
	"ky": true,
	"lag": true,
	"lg": true,
	"lkt": true,
	"ln": true,
	"lo": true,
	"lt": true,
	"lu": true,
	"luo": true,
	"luy": true,
	"lv": true,
	"mas": true,
	"mer": true,
	"mfe": true,
	"mg": true,
	"mgh": true,
	"mgo": true,
	"mk": true,
	"ml": true,
	"mn": true,
	"mr": true,
	"ms": true,
	"ms-latn-bn": true,
	"mt": true,
	"mua": true,
	"my": true,
	"naq": true,
	"nb": true,
	"nd": true,
	"ne": true,
	"nl": true,
	"nl-be": true,
	"nmg": true,
	"nn": true,
	"nnh": true,
	"nus": true,
	"nyn": true,
	"om": true,
	"or": true,
	"os": true,
	"pa": true,
	"pa-arab": true,
	"pl": true,
	"ps": true,
	"pt": true,
	"pt-pt": true,
	"rm": true,
	"rn": true,
	"ro": true,
	"rof": true,
	"ru": true,
	"ru-ua": true,
	"rw": true,
	"rwk": true,
	"sah": true,
	"saq": true,
	"sbp": true,
	"seh": true,
	"ses": true,
	"sg": true,
	"shi": true,
	"shi-latn": true,
	"si": true,
	"sk": true,
	"sl": true,
	"sn": true,
	"so": true,
	"sq": true,
	"sr": true,
	"sr-cyrl-ba": true,
	"sr-latn": true,
	"sr-latn-me": true,
	"sv": true,
	"sw": true,
	"swc": true,
	"ta": true,
	"te": true,
	"teo": true,
	"th": true,
	"ti": true,
	"ti-er": true,
	"to": true,
	"tr": true,
	"twq": true,
	"tzm": true,
	"ug": true,
	"uk": true,
	"ur": true,
	"ur-in": true,
	"uz": true,
	"uz-cyrl": true,
	"vai": true,
	"vai-latn": true,
	"vi": true,
	"vo": true,
	"vun": true,
	"wae": true,
	"xog": true,
	"yav": true,
	"yo": true,
	"yo-bj": true,
	"zgh": true,
	"zh": true,
	"zh-hans-hk": true,
	"zh-hans-mo": true,
	"zh-hans-sg": true,
	"zh-hant": true,
	"zh-hant-hk": true,
	"zh-hant-mo": true,
	"zu": true
});