define(
//begin v1.x content
{
	"BRE_displayName": "brasilianske cruzeiro (1990–1993)",
	"DEM_displayName": "tyske mark",
	"CUP_displayName": "kubanske pesos",
	"XSU_displayName": "sucre",
	"PYG_displayName": "paraguayanske guarani",
	"CLE_displayName": "chilenske escudo",
	"MDC_displayName": "moldovske cupon",
	"MDL_displayName": "moldovske leu",
	"DOP_displayName": "dominikanske pesos",
	"NGN_displayName": "nigerianske naira",
	"KZT_displayName": "kasakhstanske tenge",
	"MXV_displayName": "meksikanske unidad de inversion (UDI)",
	"LTT_displayName": "litauiske talonas",
	"LAK_displayName": "laotiske kip",
	"LKR_displayName": "srilankiske rupier",
	"AOR_displayName": "angolanske omjusterte kwanza (1995–1999)",
	"XEU_displayName": "europeisk valutaenhet",
	"XOF_symbol": "CFA",
	"USS_displayName": "amerikanske dollar (samme dag)",
	"MNT_displayName": "mongolske tugrik",
	"RHD_displayName": "rhodesiske dollar",
	"MOP_displayName": "makaoiske pataca",
	"TJR_displayName": "tadsjikiske rubler",
	"LUC_displayName": "luxemburgske konvertible franc",
	"LUL_displayName": "luxemburgske finansielle franc",
	"AON_displayName": "angolanske nye kwanza (1990–2000)",
	"TWD_symbol": "TWD",
	"BEF_displayName": "belgiske franc",
	"GHS_displayName": "ghanesiske cedi",
	"IEP_displayName": "irske pund",
	"SBD_displayName": "salomonske dollar",
	"XUA_displayName": "ADB-kontoenhet",
	"ILR_symbol": "ILR",
	"KRO_displayName": "sørkoreanske won (1945–1953)",
	"GRD_displayName": "greske drakmer",
	"NIC_displayName": "nicaraguanske cordoba (1988–1991)",
	"AZM_displayName": "aserbajdsjanske manat (1993–2006)",
	"CNY_symbol": "CNY",
	"MTP_displayName": "maltesiske pund",
	"MKN_displayName": "makedonske denarer (1992–1993)",
	"LVR_displayName": "latviske rubler",
	"GNF_displayName": "guineanske franc",
	"GIP_displayName": "gibraltarske pund",
	"SRG_displayName": "surinamske gylden",
	"BAD_displayName": "bosnisk-hercegovinske dinarer (1992–1994)",
	"FJD_displayName": "fijianske dollar",
	"BAM_displayName": "bosnisk-hercegovinske konvertible mark",
	"XBB_displayName": "europeisk monetær enhet",
	"CDF_displayName": "kongolesiske franc",
	"HRD_displayName": "kroatiske dinarer",
	"BZD_displayName": "beliziske dollar",
	"MLF_displayName": "maliske franc",
	"EGP_displayName": "egyptiske pund",
	"MVR_displayName": "maldiviske rufiyaa",
	"BAN_displayName": "nye bosnisk-hercegovinske dinarer (1994–1997)",
	"TRY_displayName": "tyrkiske lire",
	"ILR_displayName": "israelske shekler (1980–1985)",
	"SDP_displayName": "sudanesiske pund",
	"XRE_displayName": "RINET-fond",
	"ARM_displayName": "argentinsk pesos (1881–1970)",
	"NPR_displayName": "nepalske rupier",
	"PHP_displayName": "filippinske pesos",
	"WST_displayName": "samoanske tala",
	"TRL_displayName": "tyrkiske lire (1922–2005)",
	"JPY_displayName": "japanske yen",
	"TMM_displayName": "turkmenske manat (1993–2009)",
	"BGN_displayName": "bulgarske lev",
	"KYD_displayName": "caymanske dollar",
	"VUV_displayName": "vanuatiske vatu",
	"IRR_displayName": "iranske rialer",
	"DJF_displayName": "djiboutiske franc",
	"XDR_displayName": "spesielle trekkrettigheter",
	"ECS_displayName": "ecuadorianske sucre",
	"HKD_symbol": "HKD",
	"NLG_displayName": "nederlandske gylden",
	"ISJ_displayName": "gammel islandsk krone",
	"MWK_displayName": "malawiske kwacha",
	"HTG_displayName": "haitiske gourde",
	"PES_displayName": "peruvianske sol (1863–1965)",
	"LYD_displayName": "libyske dinarer",
	"BRR_displayName": "brasilianske cruzeiro",
	"XXX_displayName": "ukjent valuta",
	"IDR_displayName": "indonesiske rupier",
	"USD_displayName": "amerikanske dollar",
	"KGS_displayName": "kirgisiske som",
	"BRN_displayName": "brasilianske cruzado novo (1989–1990)",
	"CHF_displayName": "sveitsiske franc",
	"ISK_displayName": "islandske kroner",
	"LUF_displayName": "luxemburgske franc",
	"MXN_symbol": "MXN",
	"SVC_displayName": "salvadoranske colon",
	"ZMK_displayName": "zambiske kwacha (1968–2012)",
	"ZWR_displayName": "zimbabwisk dollar (2008)",
	"TOP_displayName": "tonganske paʻanga",
	"ITL_displayName": "italienske lire",
	"USN_displayName": "amerikanske dollar (neste dag)",
	"VND_symbol": "VND",
	"KWD_displayName": "kuwaitiske dinarer",
	"NIO_displayName": "nicaraguanske córdoba",
	"KMF_displayName": "komoriske franc",
	"UYI_displayName": "uruguyanske pesos (indekserte enheter)",
	"MYR_displayName": "malaysiske ringgit",
	"XFU_displayName": "franske UIC-franc",
	"GMD_displayName": "gambiske dalasi",
	"LVL_displayName": "latviske lats",
	"AUD_displayName": "australske dollar",
	"XPF_displayName": "CFP-franc",
	"LBP_displayName": "libanesiske pund",
	"ALK_displayName": "albanske lek (1946–1965)",
	"BYB_displayName": "hviterussiske nye rubler (1994–1999)",
	"MKD_displayName": "makedonske denarer",
	"GWP_displayName": "Guinea-Bissau-pesos",
	"CNY_displayName": "kinesiske yuan",
	"MAF_displayName": "marokkanske franc",
	"JOD_displayName": "jordanske dinarer",
	"OMR_displayName": "omanske rialer",
	"BOV_displayName": "bolivianske mvdol",
	"XPT_displayName": "platina",
	"AUD_symbol": "AUD",
	"NOK_displayName": "norske kroner",
	"SCR_displayName": "seychelliske rupier",
	"XBA_displayName": "europeisk sammensatt enhet",
	"CSK_displayName": "tsjekkoslovakiske koruna (hard)",
	"PLZ_displayName": "polske zloty (1950–1995)",
	"UAK_displayName": "ukrainske karbovanetz",
	"MGF_displayName": "madagassiske franc",
	"GNS_displayName": "guineanske syli",
	"YUN_displayName": "jugoslaviske konvertible dinarer",
	"GYD_displayName": "guyanske dollar",
	"QAR_displayName": "qatarske rialer",
	"ALL_displayName": "albanske lek",
	"BBD_displayName": "barbadiske dollar",
	"SSP_displayName": "sørsudanske pund",
	"RON_displayName": "rumenske leu",
	"XCD_symbol": "XCD",
	"AMD_displayName": "armenske dram",
	"ARL_displayName": "argentinske peso ley",
	"CYP_displayName": "kypriotiske pund",
	"GBP_symbol": "£",
	"SEK_displayName": "svenske kroner",
	"MMK_displayName": "myanmarske kyat",
	"ZAR_displayName": "sørafrikanske rand",
	"ECV_displayName": "ecuadorianske unidad de valor constante (UVC)",
	"CNX_symbol": "CNX",
	"BGM_displayName": "bulgarske lev (sosialist)",
	"AWG_displayName": "arubiske floriner",
	"STD_displayName": "São Tomé og Príncipe-dobra",
	"CAD_displayName": "kanadiske dollar",
	"ADP_displayName": "andorranske pesetas",
	"MRO_displayName": "mauritanske ouguiya",
	"ESB_displayName": "spanske peseta (konvertibel konto)",
	"LSL_displayName": "lesothiske loti",
	"TND_displayName": "tunisiske dinarer",
	"USD_symbol": "USD",
	"BRC_displayName": "brasilianske cruzado",
	"BMD_displayName": "bermudiske dollar",
	"BRL_displayName": "brasilianske real",
	"JMD_displayName": "jamaikanske dollar",
	"SOS_displayName": "somaliske shilling",
	"SAR_displayName": "saudiarabiske riyaler",
	"PEI_displayName": "peruvianske inti",
	"ESP_displayName": "spanske peseta",
	"HKD_displayName": "Hongkong-dollar",
	"BWP_displayName": "botswanske pula",
	"TTD_displayName": "trinidadiske dollar",
	"BRZ_displayName": "brasilianske cruzeiro (1942–1967)",
	"BSD_displayName": "bahamanske dollar",
	"BIF_displayName": "burundiske franc",
	"FRF_displayName": "franske franc",
	"DKK_displayName": "danske kroner",
	"AED_displayName": "emiratarabiske dirham",
	"AOK_displayName": "angolanske kwanza (1977–1990)",
	"ATS_displayName": "østerrikske shilling",
	"PEN_displayName": "peruanske nuevo sol",
	"CRC_displayName": "costaricanske colón",
	"PAB_displayName": "panamanske balboa",
	"CHE_displayName": "WIR euro",
	"GQE_displayName": "ekvatorialguineanske ekwele guineana",
	"ALK_symbol": "ALK",
	"DZD_displayName": "algeriske dinarer",
	"EEK_displayName": "estiske kroon",
	"YDD_displayName": "jemenittiske dinarer",
	"GHC_displayName": "ghanesisk cedi (1979–2007)",
	"MXP_displayName": "meksikanske sølvpesos (1861–1992)",
	"XPD_displayName": "palladium",
	"KRH_displayName": "sørkoreanske hwan (1953–1962)",
	"XAG_displayName": "sølv",
	"AFN_displayName": "afghansk afghani",
	"XFO_displayName": "franske gullfranc",
	"GWE_displayName": "portugisiske guinea escudo",
	"BOB_displayName": "bolivianske boliviano",
	"CAD_symbol": "CAD",
	"VND_displayName": "vietnamesiske dong",
	"AFA_displayName": "afgansk afghani (1927–2002)",
	"ZWD_displayName": "zimbabwiske dollar (1980–2008)",
	"JPY_symbol": "JPY",
	"SRD_displayName": "surinamske dollar",
	"ZRN_displayName": "zairiske nye zaire",
	"XAU_displayName": "gull",
	"KRW_symbol": "KRW",
	"BOP_displayName": "bolivianske pesos",
	"XBD_displayName": "europeisk kontoenhet (XBD)",
	"TZS_displayName": "tanzanianske shilling",
	"CNX_displayName": "Kinas folkebank dollar",
	"BOL_displayName": "bolivianske boliviano (1863–1963)",
	"XPF_symbol": "XPF",
	"ROL_displayName": "rumenske leu (1952–2006)",
	"VNN_displayName": "vietnamesiske dong (1978–1985)",
	"LRD_displayName": "liberiske dollar",
	"KRW_displayName": "sørkoreanske won",
	"SHP_displayName": "sankthelenske pund",
	"MZE_displayName": "mosambikiske escudo",
	"MZN_displayName": "mosambikiske metical",
	"SDD_displayName": "sudanesiske dinarer (1992–2007)",
	"HRK_displayName": "kroatiske kuna",
	"FKP_displayName": "falklandspund",
	"COP_displayName": "colombianske pesos",
	"YUD_displayName": "jugoslaviske dinarer (hard)",
	"YUM_displayName": "jugoslaviske noviy-dinarer",
	"THB_displayName": "thailandske baht",
	"UZS_displayName": "usbekiske som",
	"MGA_displayName": "madagassiske ariary",
	"MVP_displayName": "maldiviske rupier",
	"COU_displayName": "unidad de valor real",
	"TWD_displayName": "nye taiwanske dollar",
	"UGS_displayName": "ugandiske shilling (1966–1987)",
	"YUR_displayName": "jugoslaviske reformerte dinarer (1992–1993)",
	"ZAL_displayName": "sørafrikanske rand (finansielle)",
	"GEL_displayName": "georgiske lari",
	"ILP_displayName": "israelske pund",
	"DDM_displayName": "østtyske ostmark",
	"KES_displayName": "kenyanske shilling",
	"CUC_displayName": "kubanske konvertible pesos",
	"CZK_displayName": "tsjekkiske koruna",
	"UGX_displayName": "ugandiske shilling",
	"ILS_symbol": "ILS",
	"TMT_displayName": "turkmenske manat",
	"THB_symbol": "THB",
	"MVP_symbol": "MVP",
	"BGL_displayName": "bulgarske lev (hard)",
	"ARP_displayName": "argentinske pesos (1983–1985)",
	"RUR_displayName": "russiske rubler (1991–1998)",
	"ERN_displayName": "eritreiske nakfa",
	"ESA_displayName": "spanske peseta (A–konto)",
	"CLF_displayName": "chilenske unidades de fomento",
	"BRB_displayName": "brasilianske cruzeiro novo (1967–1986)",
	"BHD_displayName": "bahrainske dinarer",
	"SYP_displayName": "syriske pund",
	"SZL_displayName": "swazilandske lilangeni",
	"INR_displayName": "indiske rupier",
	"PTE_displayName": "portugisiske escudo",
	"KPW_displayName": "nordkoreanske won",
	"XOF_displayName": "vestafrikanske CFA-franc",
	"MXN_displayName": "meksikanske pesos",
	"RWF_displayName": "rwandiske franc",
	"ETB_displayName": "etiopiske birr",
	"LTL_displayName": "litauiske lita",
	"BND_displayName": "bruneiske dollar",
	"SUR_displayName": "sovjetiske rubler",
	"SKK_displayName": "slovakiske koruna",
	"AOA_displayName": "angolanske kwanza",
	"CVE_displayName": "kappverdiske escudos",
	"BRL_symbol": "BRL",
	"XTS_displayName": "testvalutakode",
	"CLP_displayName": "chilenske pesos",
	"HUF_displayName": "ungarske forinter",
	"TJS_displayName": "tadsjikiske somoni",
	"GBP_displayName": "britiske pund sterling",
	"TPE_displayName": "timoresiske escudo",
	"BDT_displayName": "bangladeshiske taka",
	"SGD_displayName": "singaporske dollar",
	"SLL_displayName": "sierraleonske leone",
	"XAF_displayName": "sentralafrikanske CFA-franc",
	"MTL_displayName": "maltesiske lira",
	"KHR_displayName": "kambodsjanske riel",
	"ZRZ_displayName": "zairiske zaire",
	"RSD_displayName": "serbiske dinarer",
	"BEC_displayName": "belgiske franc (konvertible)",
	"BEL_displayName": "belgiske franc (finansielle)",
	"AZN_displayName": "aserbajdsjanske manat",
	"FIM_displayName": "finske mark",
	"ZWL_displayName": "zimbabwisk dollar (2009)",
	"PKR_displayName": "pakistanske rupier",
	"UYP_displayName": "uruguayanske pesos (1975–1993)",
	"CHW_displayName": "WIR franc",
	"ZMW_displayName": "zambiske kwacha",
	"XAF_symbol": "XAF",
	"PLN_displayName": "polske zloty",
	"UAH_displayName": "ukrainske hryvnia",
	"BTN_displayName": "bhutanske ngultrum",
	"YER_displayName": "jemenittiske rialer",
	"UYU_displayName": "uruguayanske pesos",
	"CSD_displayName": "serbiske dinarer (2002–2006)",
	"VEF_displayName": "venezuelanske bolivar",
	"PGK_displayName": "papuanske kina",
	"XBC_displayName": "europeisk kontoenhet (XBC)",
	"EUR_displayName": "euro",
	"MUR_displayName": "mauritiske rupier",
	"MAD_displayName": "marokkanske dirham",
	"SDG_displayName": "sudanske pund",
	"BYR_displayName": "hviterussiske rubler",
	"VEB_displayName": "venezuelanske bolivar (1871–2008)",
	"IQD_displayName": "irakske dinarer",
	"MZM_displayName": "gamle mosambikiske metical",
	"NZD_symbol": "NZD",
	"SIT_displayName": "slovenske tolar",
	"NOK_symbol": "kr",
	"XCD_displayName": "østkaribiske dollar",
	"RUB_displayName": "russiske rubler",
	"BUK_displayName": "burmesiske kyat",
	"ILS_displayName": "nye israelske shekler",
	"INR_symbol": "INR",
	"NAD_displayName": "namibiske dollar",
	"HNL_displayName": "honduranske lempira",
	"GTQ_displayName": "guatemalanske quetzal",
	"GEK_displayName": "georgiske kupon larit",
	"EUR_symbol": "€",
	"NZD_displayName": "newzealandske dollar",
	"BGO_displayName": "bulgarske lev (1879–1952)",
	"ARA_displayName": "argentinske australer",
	"ARS_displayName": "argentinske pesos",
	"ANG_displayName": "nederlandske antillegylden"
}
//end v1.x content
);