define(
//begin v1.x content
{
	"DEM_displayName": "německá marka",
	"CUP_displayName": "kubánské peso",
	"PYG_displayName": "paraguajské guarani",
	"CLE_displayName": "chilské escudo",
	"MDL_displayName": "moldavský leu",
	"DOP_displayName": "dominikánské peso",
	"NGN_displayName": "nigerijská naira",
	"KZT_displayName": "kazašské tenge",
	"MXV_displayName": "mexická investiční jednotka",
	"LTT_displayName": "litevský talonas",
	"LAK_displayName": "laoský kip",
	"LKR_displayName": "srílanská rupie",
	"AOR_displayName": "angolská kwanza (1995–1999)",
	"XEU_displayName": "evropská měnová jednotka",
	"XOF_symbol": "CFA",
	"USS_displayName": "americký dolar (týž den)",
	"MNT_displayName": "mongolský tugrik",
	"RHD_displayName": "rhodéský dolar",
	"MOP_displayName": "macajská pataca",
	"TJR_displayName": "tádžický rubl",
	"LUC_displayName": "lucemburský konvertibilní frank",
	"LUL_displayName": "lucemburský finanční frank",
	"AON_displayName": "angolská kwanza (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "belgický frank",
	"GHS_displayName": "ghanský cedi",
	"IEP_displayName": "irská libra",
	"SBD_displayName": "šalamounský dolar",
	"GRD_displayName": "řecká drachma",
	"NIC_displayName": "nikaragujská córdoba (1988–1991)",
	"AZM_displayName": "ázerbájdžánský manat (1993–2006)",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "maltská libra",
	"MKN_displayName": "makedonský denár (1992–1993)",
	"LVR_displayName": "lotyšský rubl",
	"GNF_displayName": "guinejský frank",
	"GIP_displayName": "gibraltarská libra",
	"SRG_displayName": "surinamský zlatý",
	"BAD_displayName": "bosenský dinár (1992–1994)",
	"FJD_displayName": "fidžijský dolar",
	"BAM_displayName": "bosenská konvertibilní marka",
	"XBB_displayName": "evropská peněžní jednotka",
	"CDF_displayName": "konžský frank",
	"HRD_displayName": "chorvatský dinár",
	"BZD_displayName": "belizský dolar",
	"MLF_displayName": "malijský frank",
	"EGP_displayName": "egyptská libra",
	"CSK_symbol": "Kčs",
	"MVR_displayName": "maledivská rupie",
	"BAN_displayName": "bosenský nový dinár (1994–1997)",
	"TRY_displayName": "turecká lira",
	"ILR_displayName": "izraelský šekel (1980–1985)",
	"SDP_displayName": "súdánská libra (1957–1998)",
	"XRE_displayName": "kód fondů RINET",
	"NPR_displayName": "nepálská rupie",
	"PHP_displayName": "filipínské peso",
	"WST_displayName": "samojská tala",
	"TRL_displayName": "turecká lira (1922–2005)",
	"JPY_displayName": "japonský jen",
	"TMM_displayName": "turkmenský manat (1993–2009)",
	"BGN_displayName": "bulharský lev",
	"KYD_displayName": "kajmanský dolar",
	"VUV_displayName": "vanuatský vatu",
	"IRR_displayName": "íránský rijál",
	"DJF_displayName": "džibutský frank",
	"XDR_displayName": "SDR",
	"HKD_symbol": "HK$",
	"ISJ_displayName": "islandská koruna (1918–1981)",
	"MWK_displayName": "malawijská kwacha",
	"HTG_displayName": "haitský gourde",
	"PES_displayName": "peruánský sol (1863–1965)",
	"LYD_displayName": "libyjský dinár",
	"XXX_displayName": "neznámá měna",
	"IDR_displayName": "indonéská rupie",
	"USD_displayName": "americký dolar",
	"KGS_displayName": "kyrgyzský som",
	"CHF_displayName": "švýcarský frank",
	"ISK_displayName": "islandská koruna",
	"LUF_displayName": "lucemburský frank",
	"MXN_symbol": "MX$",
	"SVC_displayName": "salvadorský colón",
	"ZMK_displayName": "zambijská kwacha (1968–2012)",
	"ZWR_displayName": "zimbabwský dolar (2008)",
	"TOP_displayName": "tonžská paanga",
	"ITL_displayName": "italská lira",
	"USN_displayName": "americký dolar (příští den)",
	"VND_symbol": "VND",
	"KWD_displayName": "kuvajtský dinár",
	"NIO_displayName": "nikaragujská córdoba",
	"KMF_displayName": "komorský frank",
	"MYR_displayName": "malajsijský ringgit",
	"XEU_symbol": "ECU",
	"XFU_displayName": "francouzský UIC frank",
	"GMD_displayName": "gambijský dalasi",
	"LVL_displayName": "lotyšský lat",
	"AUD_displayName": "australský dolar",
	"XPF_displayName": "CFP frank",
	"LBP_displayName": "libanonská libra",
	"ALK_displayName": "albánské lek (1946–1965)",
	"BYB_displayName": "běloruský rubl (1994–1999)",
	"MKD_displayName": "makedonský denár",
	"GWP_displayName": "guinejsko-bissauské peso",
	"CNY_displayName": "čínský jüan",
	"MAF_displayName": "marocký frank",
	"JOD_displayName": "jordánský dinár",
	"OMR_displayName": "ománský rijál",
	"BOV_displayName": "bolivijský mvdol",
	"XPT_displayName": "platina",
	"AUD_symbol": "AU$",
	"NOK_displayName": "norská koruna",
	"SCR_displayName": "seychelská rupie",
	"XBA_displayName": "evropská smíšená jednotka",
	"CSK_displayName": "československá koruna",
	"PLZ_displayName": "polský zlotý (1950–1995)",
	"UAK_displayName": "ukrajinský karbovanec",
	"MGF_displayName": "madagaskarský frank",
	"GNS_displayName": "guinejský syli",
	"YUN_displayName": "jugoslávský konvertibilní dinár (1990–1992)",
	"GYD_displayName": "guyanský dolar",
	"QAR_displayName": "katarský rijál",
	"ALL_displayName": "albánský lek",
	"BBD_displayName": "barbadoský dolar",
	"SSP_displayName": "jihosúdánská libra",
	"RON_displayName": "rumunské leu",
	"XCD_symbol": "EC$",
	"AMD_displayName": "arménský dram",
	"CYP_displayName": "kyperská libra",
	"GBP_symbol": "£",
	"SEK_displayName": "švédská koruna",
	"MMK_displayName": "myanmarský kyat",
	"ZAR_displayName": "jihoafrický rand",
	"AWG_displayName": "arubský zlatý",
	"STD_displayName": "svatotomášská dobra",
	"CAD_displayName": "kanadský dolar",
	"ADP_displayName": "andorrská peseta",
	"MRO_displayName": "mauritánská ouguiya",
	"ESB_displayName": "španělská peseta (konvertibilní účet)",
	"LSL_displayName": "lesothský loti",
	"TND_displayName": "tuniský dinár",
	"USD_symbol": "US$",
	"BMD_displayName": "bermudský dolar",
	"BRL_displayName": "brazilský real",
	"JMD_displayName": "jamajský dolar",
	"SOS_displayName": "somálský šilink",
	"SAR_displayName": "saúdský rijál",
	"PEI_displayName": "peruánská inti",
	"ESP_displayName": "španělská peseta",
	"HKD_displayName": "hongkongský dolar",
	"BWP_displayName": "botswanská pula",
	"TTD_displayName": "trinidadský dolar",
	"BSD_displayName": "bahamský dolar",
	"BIF_displayName": "burundský frank",
	"FRF_displayName": "francouzský frank",
	"DKK_displayName": "dánská koruna",
	"AED_displayName": "SAE dirham",
	"AOK_displayName": "angolská kwanza (1977–1991)",
	"ATS_displayName": "rakouský šilink",
	"PEN_displayName": "peruánský nový sol",
	"CRC_displayName": "kostarický colón",
	"PAB_displayName": "panamská balboa",
	"DZD_displayName": "alžírský dinár",
	"EEK_displayName": "estonská koruna",
	"YDD_displayName": "jemenský dinár",
	"GHC_displayName": "ghanský cedi (1979–2007)",
	"MXP_displayName": "mexické stříbrné peso (1861–1992)",
	"XPD_displayName": "palladium",
	"XAG_displayName": "stříbro",
	"AFN_displayName": "afghánský afghán",
	"XFO_displayName": "francouzský zlatý frank",
	"BOB_displayName": "bolivijský boliviano",
	"XBB_symbol": "EMU",
	"CAD_symbol": "CA$",
	"VND_displayName": "vietnamský dong",
	"AFA_displayName": "afghánský afghán (1927–2002)",
	"ZWD_displayName": "zimbabwský dolar (1980–2008)",
	"JPY_symbol": "JP¥",
	"SRD_displayName": "surinamský dolar",
	"ZRN_displayName": "zairský nový zaire (1993–1998)",
	"XAU_displayName": "zlato",
	"KRW_symbol": "₩",
	"BOP_displayName": "bolivijské peso",
	"XBD_displayName": "evropská jednotka účtu 17 (XBD)",
	"TZS_displayName": "tanzanský šilink",
	"BOL_displayName": "bolivijský boliviano (1863–1963)",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "rumunské leu (1952–2006)",
	"VNN_displayName": "vietnamský dong (1978–1985)",
	"LRD_displayName": "liberijský dolar",
	"KRW_displayName": "jihokorejský won",
	"SHP_displayName": "svatohelenská libra",
	"MZE_displayName": "mosambický escudo",
	"MZN_displayName": "mozambický metical",
	"SDD_displayName": "súdánský dinár (1992–2007)",
	"HRK_displayName": "chorvatská kuna",
	"FKP_displayName": "falklandská libra",
	"COP_displayName": "kolumbijské peso",
	"YUD_displayName": "jugoslávský dinár (1966–1990)",
	"YUM_displayName": "jugoslávský nový dinár (1994–2002)",
	"THB_displayName": "thajský baht",
	"UZS_displayName": "uzbecký sum",
	"MGA_displayName": "madagaskarský ariary",
	"TWD_displayName": "tchajwanský dolar",
	"UGS_displayName": "ugandský šilink (1966–1987)",
	"ZAL_displayName": "jihoafrický finanční rand",
	"GEL_displayName": "gruzínské lari",
	"ILP_displayName": "izraelská libra",
	"DDM_displayName": "východoněmecká marka",
	"KES_displayName": "keňský šilink",
	"CUC_displayName": "kubánské konvertibilní peso",
	"CZK_displayName": "česká koruna",
	"UGX_displayName": "ugandský šilink",
	"ILS_symbol": "₪",
	"TMT_displayName": "turkmenský manat",
	"THB_symbol": "THB",
	"ARP_displayName": "argentinské peso (1983–1985)",
	"RUR_displayName": "ruský rubl (1991–1998)",
	"ERN_displayName": "eritrejská nakfa",
	"ESA_displayName": "španělská peseta („A“ účet)",
	"BHD_displayName": "bahrajnský dinár",
	"SYP_displayName": "syrská libra",
	"SZL_displayName": "svazijský lilangeni",
	"INR_displayName": "indická rupie",
	"PTE_displayName": "portugalské escudo",
	"KPW_displayName": "severokorejský won",
	"XOF_displayName": "CFA/BCEAO frank",
	"MXN_displayName": "mexické peso",
	"RWF_displayName": "rwandský frank",
	"ETB_displayName": "etiopský birr",
	"LTL_displayName": "litevský litas",
	"BND_displayName": "brunejský dolar",
	"SUR_displayName": "sovětský rubl",
	"SKK_displayName": "slovenská koruna",
	"AOA_displayName": "angolská kwanza",
	"CVE_displayName": "kapverdské escudo",
	"BRL_symbol": "R$",
	"XTS_displayName": "kód zvlášť vyhrazený pro testovací účely",
	"CLP_displayName": "chilské peso",
	"HUF_displayName": "maďarský forint",
	"TJS_displayName": "tádžické somoni",
	"GBP_displayName": "britská libra",
	"TPE_displayName": "timorské escudo",
	"BDT_displayName": "bangladéšská taka",
	"SGD_displayName": "singapurský dolar",
	"SLL_displayName": "sierro-leonský leone",
	"XAF_displayName": "CFA/BEAC frank",
	"MTL_displayName": "maltská lira",
	"ZRZ_displayName": "zairský zaire (1971–1993)",
	"KHR_displayName": "kambodžský riel",
	"RSD_displayName": "srbský dinár",
	"BEC_displayName": "belgický konvertibilní frank",
	"BEL_displayName": "belgický finanční frank",
	"AZN_displayName": "ázerbájdžánský manat",
	"FIM_displayName": "finská marka",
	"ZWL_displayName": "zimbabwský dolar (2009)",
	"PKR_displayName": "pákistánská rupie",
	"UYP_displayName": "uruguayské peso (1975–1993)",
	"ZMW_displayName": "zambijská kwacha",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "polský zlotý",
	"UAH_displayName": "ukrajinská hřivna",
	"BTN_displayName": "bhútánský ngultrum",
	"YER_displayName": "jemenský rijál",
	"UYU_displayName": "uruguayské peso",
	"VEF_displayName": "venezuelský bolívar",
	"PGK_displayName": "papuánská nová kina",
	"XBC_displayName": "evropská jednotka účtu 9 (XBC)",
	"EUR_displayName": "euro",
	"MUR_displayName": "mauricijská rupie",
	"MAD_displayName": "marocký dinár",
	"SDG_displayName": "súdánská libra",
	"BYR_displayName": "běloruský rubl",
	"VEB_displayName": "venezuelský bolívar (1871–2008)",
	"IQD_displayName": "irácký dinár",
	"MZM_displayName": "mosambický metical (1980–2006)",
	"NZD_symbol": "NZ$",
	"SIT_displayName": "slovinský tolar",
	"CZK_symbol": "Kč",
	"XCD_displayName": "východokaribský dolar",
	"RUB_displayName": "ruský rubl",
	"BUK_displayName": "barmský kyat",
	"ILS_displayName": "izraelský nový šekel",
	"INR_symbol": "INR",
	"NAD_displayName": "namibijský dolar",
	"HNL_displayName": "honduraská lempira",
	"GTQ_displayName": "guatemalský quetzal",
	"EUR_symbol": "€",
	"NZD_displayName": "novozélandský dolar",
	"ARA_displayName": "argentinský austral",
	"ARS_displayName": "argentinské peso",
	"ANG_displayName": "zlatý Nizozemských Antil"
}
//end v1.x content
);