define(
//begin v1.x content
{
	"BRE_displayName": "Cruzeiro Brasiliano (1990–1993)",
	"DEM_displayName": "Marco Tedesco",
	"CUP_displayName": "Peso Cubano",
	"PYG_displayName": "Guaraní del Paraguay",
	"MDL_displayName": "Leu Moldavo",
	"DOP_displayName": "Peso Dominicano",
	"NGN_displayName": "Naira Nigeriana",
	"KZT_displayName": "Tenge Kazaco",
	"MXV_displayName": "Unidad de Inversion (UDI) Messicana",
	"LTT_displayName": "Talonas Lituani",
	"LAK_displayName": "Kip Laotiano",
	"LKR_displayName": "Rupia di Sri Lanka",
	"AOR_displayName": "Kwanza Reajustado Angolano (1995–1999)",
	"XOF_symbol": "CFA",
	"USS_displayName": "Dollaro Statunitense (Same day)",
	"MNT_displayName": "Tugrik Mongolo",
	"RHD_displayName": "Dollaro della Rhodesia",
	"MOP_displayName": "Pataca di Macao",
	"TJR_displayName": "Rublo del Tajikistan",
	"LUC_displayName": "Franco Convertibile del Lussemburgo",
	"LUL_displayName": "Franco Finanziario del Lussemburgo",
	"AON_displayName": "Nuovo Kwanza Angolano (1990–2000)",
	"TWD_symbol": "NT$",
	"BEF_displayName": "Franco Belga",
	"GHS_displayName": "Cedi ghanese",
	"IEP_displayName": "Sterlina irlandese",
	"SBD_displayName": "Dollaro delle Isole Solomon",
	"GRD_displayName": "Dracma Greca",
	"NIC_displayName": "Cordoba Nicaraguense",
	"AZM_displayName": "Manat Azero (1993–2006)",
	"CNY_symbol": "CN¥",
	"MTP_displayName": "Sterlina Maltese",
	"LVR_displayName": "Rublo Lettone",
	"GNF_displayName": "Franco della Guinea",
	"GIP_displayName": "Sterlina di Gibilterra",
	"SRG_displayName": "Fiorino del Suriname",
	"BAD_displayName": "Dinar Bosnia-Herzegovina",
	"FJD_displayName": "Dollaro delle Figi",
	"BAM_displayName": "Marco Conv. Bosnia-Erzegovina",
	"XBB_displayName": "Unità monetaria europea",
	"CDF_displayName": "Franco Congolese",
	"HRD_displayName": "Dinaro Croato",
	"ITL_pattern": "¤ #,##0.00",
	"BZD_displayName": "Dollaro del Belize",
	"MLF_displayName": "Franco di Mali",
	"EGP_displayName": "Sterlina Egiziana",
	"MVR_displayName": "Rufiyaa delle Maldive",
	"TRY_displayName": "Nuova Lira Turca",
	"XRE_displayName": "Fondi RINET",
	"NPR_displayName": "Rupia Nepalese",
	"PHP_displayName": "Peso delle Filippine",
	"WST_displayName": "Tala della Samoa Occidentale",
	"TRL_displayName": "Lira Turca",
	"JPY_displayName": "Yen Giapponese",
	"TMM_displayName": "Manat Turkmeno (1993–2009)",
	"BGN_displayName": "Nuovo Lev Bulgaro",
	"KYD_displayName": "Dollaro delle Isole Cayman",
	"VUV_displayName": "Vatu di Vanuatu",
	"IRR_displayName": "Rial Iraniano",
	"DJF_displayName": "Franco Gibutiano",
	"XDR_displayName": "Diritti Speciali di Incasso",
	"ECS_displayName": "Sucre dell’Ecuador",
	"HKD_symbol": "HK$",
	"NLG_displayName": "Fiorino Olandese",
	"MWK_displayName": "Kwacha Malawiano",
	"HTG_displayName": "Gourde Haitiano",
	"PES_displayName": "Sol Peruviano",
	"LYD_displayName": "Dinaro Libico",
	"BRR_displayName": "Cruzeiro Brasiliano",
	"XXX_displayName": "Valuta sconosciuta",
	"IDR_displayName": "Rupia Indonesiana",
	"USD_displayName": "Dollaro Statunitense",
	"KGS_displayName": "Som Kirghiso",
	"BRN_displayName": "Cruzado Novo Brasiliano",
	"CHF_displayName": "Franco Svizzero",
	"ISK_displayName": "Corona Islandese",
	"LUF_displayName": "Franco del Lussemburgo",
	"MXN_symbol": "MX$",
	"SVC_displayName": "Colón Salvadoregno",
	"ZMK_displayName": "Kwacha dello Zambia (1968–2012)",
	"TOP_displayName": "Paʻanga di Tonga",
	"ITL_displayName": "Lira Italiana",
	"USN_displayName": "Dollaro Statunitense (Next day)",
	"VND_symbol": "₫",
	"KWD_displayName": "Dinaro Kuwaitiano",
	"NIO_displayName": "Córdoba Nicaraguense",
	"KMF_displayName": "Franco Comoriano",
	"UYI_displayName": "Peso uruguaiano in unità indicizzate",
	"MYR_displayName": "Ringgit della Malesia",
	"XFU_displayName": "Franco UIC Francese",
	"GMD_displayName": "Dalasi del Gambia",
	"LVL_displayName": "Lats Lettone",
	"AUD_displayName": "Dollaro Australiano",
	"XPF_displayName": "Franco CFP",
	"LBP_displayName": "Sterlina Libanese",
	"BYB_displayName": "Nuovo Rublo Bielorussia (1994–1999)",
	"MKD_displayName": "Dinaro Macedone",
	"GWP_displayName": "Peso della Guinea-Bissau",
	"CNY_displayName": "Renmimbi Cinese",
	"MAF_displayName": "Franco Marocchino",
	"JOD_displayName": "Dinaro Giordano",
	"OMR_displayName": "Rial dell'Oman",
	"BOV_displayName": "Mvdol Boliviano",
	"XPT_displayName": "Platino",
	"AUD_symbol": "A$",
	"NOK_displayName": "Corona Norvegese",
	"SCR_displayName": "Rupia delle Seychelles",
	"XBA_displayName": "Unità composita europea",
	"CSK_displayName": "Corona forte cecoslovacca",
	"PLZ_displayName": "Zloty Polacco (1950–1995)",
	"UAK_displayName": "Karbovanetz Ucraino",
	"MGF_displayName": "Franco Malgascio",
	"GNS_displayName": "Syli della Guinea",
	"YUN_displayName": "Dinaro Convertibile Yugoslavo",
	"GYD_displayName": "Dollaro della Guyana",
	"QAR_displayName": "Rial del Qatar",
	"ALL_displayName": "Lek Albanese",
	"BBD_displayName": "Dollaro di Barbados",
	"SSP_displayName": "Sterlina sudsudanese",
	"RON_displayName": "Leu Rumeno",
	"XCD_symbol": "EC$",
	"AMD_displayName": "Dram Armeno",
	"CYP_displayName": "Sterlina Cipriota",
	"GBP_symbol": "£",
	"SEK_displayName": "Corona Svedese",
	"MMK_displayName": "Kyat di Myanmar",
	"ZAR_displayName": "Rand Sudafricano",
	"ECV_displayName": "Unidad de Valor Constante (UVC) dell’Ecuador",
	"AWG_displayName": "Fiorino di Aruba",
	"STD_displayName": "Dobra di Sao Tomé e Principe",
	"CAD_displayName": "Dollaro Canadese",
	"ADP_displayName": "Peseta Andorrana",
	"MRO_displayName": "Ouguiya della Mauritania",
	"ESB_displayName": "Peseta Spagnola Account Convertibile",
	"LSL_displayName": "Loti del Lesotho",
	"TND_displayName": "Dinaro Tunisino",
	"USD_symbol": "US$",
	"BRC_displayName": "Cruzado Brasiliano",
	"BMD_displayName": "Dollaro delle Bermuda",
	"BRL_displayName": "Real Brasiliano",
	"JMD_displayName": "Dollaro Giamaicano",
	"SOS_displayName": "Scellino Somalo",
	"SAR_displayName": "Ryal Saudita",
	"PEI_displayName": "Inti Peruviano",
	"ESP_displayName": "Peseta Spagnola",
	"HKD_displayName": "Dollaro di Hong Kong",
	"BWP_displayName": "Pula del Botswana",
	"TTD_displayName": "Dollaro di Trinidad e Tobago",
	"BSD_displayName": "Dollaro delle Bahamas",
	"BIF_displayName": "Franco del Burundi",
	"FRF_displayName": "Franco Francese",
	"DKK_displayName": "Corona Danese",
	"AED_displayName": "Dirham degli Emirati Arabi Uniti",
	"AOK_displayName": "Kwanza Angolano (1977–1990)",
	"ATS_displayName": "Scellino Austriaco",
	"PEN_displayName": "Sol Nuevo Peruviano",
	"CRC_displayName": "Colón Costaricano",
	"PAB_displayName": "Balboa di Panama",
	"GQE_displayName": "Ekwele della Guinea Equatoriale",
	"DZD_displayName": "Dinaro Algerino",
	"EEK_displayName": "Corona dell’Estonia",
	"YDD_displayName": "Dinaro dello Yemen",
	"GHC_displayName": "Cedi del Ghana",
	"MXP_displayName": "Peso messicano d’argento (1861–1992)",
	"XPD_displayName": "Palladio",
	"XAG_displayName": "Argento",
	"AFN_displayName": "Afghani",
	"XFO_displayName": "Franco Oro Francese",
	"ITL_group": ".",
	"GWE_displayName": "Escudo della Guinea portoghese",
	"BOB_displayName": "Boliviano",
	"CAD_symbol": "CA$",
	"VND_displayName": "Dong Vietnamita",
	"AFA_displayName": "Afgani (1927–2002)",
	"ZWD_displayName": "Dollaro dello Zimbabwe",
	"JPY_symbol": "JP¥",
	"SRD_displayName": "Dollaro Surinamese",
	"ZRN_displayName": "Nuovo Zaire dello Zaire",
	"XAU_displayName": "Oro",
	"KRW_symbol": "₩",
	"BOP_displayName": "Peso Boliviano",
	"XBD_displayName": "Unità di acconto europea (XBD)",
	"TZS_displayName": "Scellino della Tanzania",
	"XPF_symbol": "CFPF",
	"ROL_displayName": "Leu della Romania",
	"LRD_displayName": "Dollaro Liberiano",
	"KRW_displayName": "Won Sudcoreano",
	"SHP_displayName": "Sterlina di Sant’Elena",
	"MZE_displayName": "Escudo del Mozambico",
	"MZN_displayName": "Metical mozambicano",
	"SDD_displayName": "Dinaro Sudanese",
	"HRK_displayName": "Kuna Croata",
	"FKP_displayName": "Sterlina delle Falkland",
	"COP_displayName": "Peso Colombiano",
	"YUD_displayName": "Dinaro Forte Yugoslavo",
	"YUM_displayName": "Dinaro Noviy Yugoslavo",
	"THB_displayName": "Baht Tailandese",
	"UZS_displayName": "Sum dell’Uzbekistan",
	"MGA_displayName": "Ariary Malgascio",
	"TWD_displayName": "Nuovo dollaro taiwanese",
	"UGS_displayName": "Scellino Ugandese (1966–1987)",
	"ZAL_displayName": "Rand Sudafricano (finanziario)",
	"GEL_displayName": "Lari Georgiano",
	"ILP_displayName": "Sterlina Israeliana",
	"DDM_displayName": "Ostmark della Germania Orientale",
	"KES_displayName": "Scellino Keniota",
	"CUC_displayName": "Peso Cubano Convertibile",
	"CZK_displayName": "Corona Ceca",
	"UGX_displayName": "Scellino Ugandese",
	"ILS_symbol": "₪",
	"TMT_displayName": "Manat Turkmeno",
	"THB_symbol": "฿",
	"BGL_displayName": "Lev Bulgaro",
	"ARP_displayName": "Peso Argentino (vecchio Cod.)",
	"RUR_displayName": "Rublo della CSI",
	"ERN_displayName": "Nakfa Eritreo",
	"ESA_displayName": "Peseta Spagnola Account",
	"CLF_displayName": "Unidades de Fomento Chilene",
	"BRB_displayName": "Cruzeiro Novo Brasiliano (1967–1986)",
	"BHD_displayName": "Dinaro del Bahraini",
	"SYP_displayName": "Sterlina Siriana",
	"SZL_displayName": "Lilangeni dello Swaziland",
	"INR_displayName": "Rupia Indiana",
	"PTE_displayName": "Escudo Portoghese",
	"KPW_displayName": "Won Nordcoreano",
	"XOF_displayName": "Franco CFA BCEAO",
	"MXN_displayName": "Peso Messicano",
	"RWF_displayName": "Franco Ruandese",
	"ETB_displayName": "Birr Etiopico",
	"LTL_displayName": "Litas Lituano",
	"BND_displayName": "Dollaro del Brunei",
	"SUR_displayName": "Rublo Sovietico",
	"SKK_displayName": "Corona Slovacca",
	"AOA_displayName": "Kwanza Angolano",
	"CVE_displayName": "Escudo del Capo Verde",
	"BRL_symbol": "R$",
	"XTS_displayName": "Codice di verifica della valuta",
	"CLP_displayName": "Peso Cileno",
	"HUF_displayName": "Fiorino Ungherese",
	"TJS_displayName": "Somoni del Tajikistan",
	"GBP_displayName": "Sterlina Inglese",
	"TPE_displayName": "Escudo di Timor",
	"BDT_displayName": "Taka Bangladese",
	"SGD_displayName": "Dollaro di Singapore",
	"SLL_displayName": "Leone della Sierra Leone",
	"XAF_displayName": "Franco CFA BEAC",
	"MTL_displayName": "Lira Maltese",
	"KHR_displayName": "Riel Cambogiano",
	"ZRZ_displayName": "Zaire dello Zaire",
	"RSD_displayName": "Dinaro Serbo",
	"BEC_displayName": "Franco Belga (convertibile)",
	"BEL_displayName": "Franco Belga (finanziario)",
	"AZN_displayName": "Manat Azero",
	"FIM_displayName": "Markka Finlandese",
	"ZWL_displayName": "Dollaro Zimbabwiano (2009)",
	"PKR_displayName": "Rupia del Pakistan",
	"UYP_displayName": "Peso Uruguaiano (1975–1993)",
	"ZMW_displayName": "Kwacha dello Zambia",
	"XAF_symbol": "FCFA",
	"PLN_displayName": "Zloty Polacco",
	"UAH_displayName": "Grivnia Ucraina",
	"BTN_displayName": "Ngultrum Butanese",
	"YER_displayName": "Rial dello Yemen",
	"UYU_displayName": "Peso Uruguaiano",
	"CSD_displayName": "Antico Dinaro Serbo",
	"VEF_displayName": "Bolívar Venezuelano",
	"PGK_displayName": "Kina della Papua Nuova Guinea",
	"XBC_displayName": "Unità di acconto europea (XBC)",
	"EUR_displayName": "Euro",
	"MUR_displayName": "Rupia Mauriziana",
	"MAD_displayName": "Dirham Marocchino",
	"SDG_displayName": "Sterlina Sudanese",
	"BYR_displayName": "Rublo Bielorussia",
	"VEB_displayName": "Bolivar Venezuelano (1871–2008)",
	"IQD_displayName": "Dinaro Iracheno",
	"NZD_symbol": "NZ$",
	"SIT_displayName": "Tallero Sloveno",
	"XCD_displayName": "Dollaro dei Caraibi Orientali",
	"RUB_displayName": "Rublo Russo",
	"BUK_displayName": "Kyat Birmano",
	"ILS_displayName": "Nuovo Shequel Israeliano",
	"INR_symbol": "₹",
	"NAD_displayName": "Dollaro Namibiano",
	"HNL_displayName": "Lempira Honduregna",
	"GTQ_displayName": "Quetzal Guatemalteco",
	"GEK_displayName": "Kupon Larit Georgiano",
	"NZD_displayName": "Dollaro Neozelandese",
	"ARA_displayName": "Austral Argentino",
	"ARS_displayName": "Peso Argentino",
	"ITL_decimal": ",",
	"ANG_displayName": "Fiorino delle Antille Olandesi"
}
//end v1.x content
);